'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TEST=new URLSearchParams(location.search).get('test')==='1';
const KEY='tta_v2';
const THEMES={
 meadow:{name:'MEADOW RUSH',sky1:'#59c9ff',sky2:'#d9f6ff',ground:'#56bd6b',ground2:'#2e8446',accent:'#f6d85f',enemy:['#8d69ff','#ff6b8d','#ff9e54']},
 desert:{name:'DESERT DASH',sky1:'#ffbf6b',sky2:'#ffe8bd',ground:'#d89b4b',ground2:'#95602e',accent:'#5ee3ff',enemy:['#7e5cff','#ef5f4f','#cd7b33']},
 ice:{name:'ICE CITADEL',sky1:'#7edff5',sky2:'#dffbff',ground:'#bceff7',ground2:'#65a6c5',accent:'#8b7cff',enemy:['#7b6cff','#ff75a7','#4f9cff']},
 lava:{name:'LAVA FORT',sky1:'#4e2036',sky2:'#140f22',ground:'#5e2c29',ground2:'#2a1821',accent:'#ffca5e',enemy:['#b45cff','#ff574e','#ff9b45']}
};
const I={
 en:{welcome:'Welcome back',coins:'Coins',streak:'Streak',battleMode:'BATTLE MODE',subtitle:'Defend the base. Power up with maths.',howText:'Enemies keep moving while you play. Tap targets, spend skills, grab supplies, and answer a maths challenge about every 20–30 seconds.',play:'PLAY BATTLE',load:'Load',collection:'Collection',progress:'My Progress',classboard:'Classboard',settings:'Settings',todayMissions:"Today’s missions",bossIncoming:'BOSS INCOMING',bossHint:'Keep clearing minions!',tapSupply:'Tap the supply!',powerShot:'Power Shot',shield:'Shield',bomb:'Bomb',runComplete:'RUN COMPLETE',accuracy:'Accuracy',bestCombo:'Best combo',coinsEarned:'Coins earned',bossDamage:'Boss damage',retry:'Play again',challengeFriend:'Challenge a friend',home:'Home',share:'Share',collectionHint:'Unlock looks with coins. Pet bonuses stay tiny so battles remain fair.',avatars:'Avatars',pets:'Pets',lifetimeAccuracy:'Lifetime accuracy',factsAnswered:'Facts answered',weakFacts:'Facts to practise',boardHint:'No account needed. Import classmates’ challenge codes on this device.',import:'Import',rotate:'Rotate your phone',rotateText:'Battle Arena is designed for landscape mode.',continueAnyway:'Continue anyway',setupTitle:'Player setup',nickname:'Nickname',focus:'Training focus',save:'Save',missionA:'Answer 12 facts',missionB:'Reach 5 combo',missionC:'Fight the Boss',focusAuto:'Adaptive 1×1–10×10',correct:'CORRECT!',wrong:'NOT QUITE',answerWas:'Answer:',armyPlus:'+ soldiers',energyPlus:'+ energy',bossShield:'Boss shield broken!',bossPhase:'BOSS PHASE',supply:'SUPPLY!',skillReady:'Skill ready!',notEnough:'Need more energy',great:'Victory run!',practice:'Keep powering up!',challengeLoaded:'Challenge loaded',invalidCode:'Invalid challenge code',imported:'Classmate imported',noBoard:'No classmates imported yet.',selected:'Selected',need:'Need',unlocked:'Unlocked',lane:'Choose the safe lane',monster:'Blast the correct monster',bridge:'Build the correct bridge',balloon:'Pop the correct balloon',inverse:'Find the missing number',type:'Type the answer',slow:'SLOW-MOTION',target:'TARGET',bossDown:'BOSS DOWN!',stageClear:'Stage clear!',loot:'BONUS LOOT',tapTarget:'Tap an enemy to focus fire'},
 zh:{welcome:'歡迎返嚟',coins:'金幣',streak:'連續日數',battleMode:'戰鬥模式',subtitle:'守住基地，用乘數提升戰力。',howText:'敵人會持續進攻。你可以點選目標、使用技能、搶補給；大約每 20–30 秒先出現一次乘數挑戰。',play:'開始戰鬥',load:'載入',collection:'收藏',progress:'學習進度',classboard:'同學榜',settings:'設定',todayMissions:'今日任務',bossIncoming:'BOSS 即將出現',bossHint:'小怪仍然會繼續進攻！',tapSupply:'撳補給箱！',powerShot:'重炮',shield:'護盾',bomb:'炸彈',runComplete:'戰鬥完成',accuracy:'正確率',bestCombo:'最高連擊',coinsEarned:'獲得金幣',bossDamage:'Boss 傷害',retry:'再玩一局',challengeFriend:'挑戰同學',home:'主頁',share:'分享',collectionHint:'用金幣解鎖外觀；寵物只提供非常輕微加成，保持公平。',avatars:'角色',pets:'寵物',lifetimeAccuracy:'總正確率',factsAnswered:'已完成題目',weakFacts:'需要多練',boardHint:'毋須帳戶。將同學 Challenge Code 匯入本機即可。',import:'加入',rotate:'請將手機轉為橫向',rotateText:'Battle Arena 以橫向畫面設計。',continueAnyway:'照樣繼續',setupTitle:'玩家設定',nickname:'暱稱',focus:'練習重點',save:'儲存',missionA:'完成 12 題',missionB:'達成 5 Combo',missionC:'迎戰 Boss',focusAuto:'自動 1×1–10×10',correct:'答啱！',wrong:'差少少',answerWas:'正確答案：',armyPlus:'士兵 +',energyPlus:'能量 +',bossShield:'Boss 護盾破壞！',bossPhase:'BOSS 階段',supply:'補給！',skillReady:'技能可用！',notEnough:'能量不足',great:'漂亮一戰！',practice:'繼續升級！',challengeLoaded:'挑戰已載入',invalidCode:'Challenge Code 無效',imported:'已加入同學成績',noBoard:'暫時未加入同學成績。',selected:'使用中',need:'需要',unlocked:'已解鎖',lane:'揀正確路線',monster:'攻擊正確怪物',bridge:'砌出正確橋樑',balloon:'篤爆正確氣球',inverse:'找出缺少的數字',type:'輸入答案',slow:'慢動作',target:'鎖定',bossDown:'BOSS 擊破！',stageClear:'過關！',loot:'額外戰利品',tapTarget:'點擊敵人集中火力'}
};
const defaults={nickname:'',lang:'en',coins:0,xp:0,streak:0,lastDay:'',avatar:'🧑‍🚀',pet:'',music:true,focus:'auto',answered:0,correct:0,weak:{},board:[],daily:{day:'',answers:0,maxCombo:0,boss:false},loot:0};
let data=load(),game=null,raf=0,lastTs=0,audio=null,musicTimer=0,lastResult=null,pendingChallenge=null,rotateDismissed=false,canvas,ctx,dpr=1,W=0,H=0,entityId=1;
function t(k){return I[data.lang]?.[k]||I.en[k]||k}
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {...defaults}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
function today(){return new Date().toISOString().slice(0,10)}
function ensureDaily(){if(data.daily.day!==today())data.daily={day:today(),answers:0,maxCombo:0,boss:false}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function applyLang(){document.documentElement.lang=data.lang==='zh'?'zh-Hant':'en';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#langBtn').textContent=data.lang==='en'?'繁中':'EN';$('#challengeInput').placeholder=data.lang==='zh'?'貼上 Challenge Code':'Paste challenge code';$('#boardCode').placeholder=data.lang==='zh'?'貼上同學 Challenge Code':'Paste classmate code';renderLobby();updateSkillLabels()}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='lobby')renderLobby();if(id==='collection')renderCollection();if(id==='progress')renderProgress();if(id==='board')renderBoard();if(id==='game')resizeCanvas();checkRotate()}
function renderLobby(){ensureDaily();$('#heroAvatar').textContent=data.avatar+(data.pet||'');$('#nickLabel').textContent=data.nickname||'Player';$('#coinsLabel').textContent=data.coins;$('#xpLabel').textContent=data.xp;$('#streakLabel').textContent=data.streak+'🔥';$('#focusLabel').textContent=data.focus==='auto'?t('focusAuto'):'×'+data.focus;const d=data.daily,ms=[{n:t('missionA'),v:Math.min(d.answers,12),m:12},{n:t('missionB'),v:Math.min(d.maxCombo,5),m:5},{n:t('missionC'),v:d.boss?1:0,m:1}];$('#missions').innerHTML=ms.map(m=>`<div class="mission"><b>${esc(m.n)}</b><div class="muted">${m.v}/${m.m}</div><div class="missionBar"><i style="width:${m.v/m.m*100}%"></i></div></div>`).join('')}
function openSetup(){$('#nicknameInput').value=data.nickname;$('#focusSelect').value=data.focus;$('#setupModal').classList.remove('hidden')}
function checkRotate(){const gameish=$('#game').classList.contains('active')||$('#lobby').classList.contains('active'),portrait=innerHeight>innerWidth&&innerWidth<900;if(gameish&&portrait&&!rotateDismissed)$('#rotatePrompt').classList.remove('hidden');else $('#rotatePrompt').classList.add('hidden')}
function seedRand(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let z=x;z=Math.imul(z^(z>>>15),z|1);z^=z+Math.imul(z^(z>>>7),z|61);return((z^(z>>>14))>>>0)/4294967296}}
function weightedFact(rng){let a,b;const f=Number(data.focus)||0;if(f){a=f;b=1+Math.floor(rng()*10)}else{const pool=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const k=i+'x'+j,w=1+Math.min(5,Number(data.weak[k]||0));for(let n=0;n<w;n++)pool.push([i,j])}[a,b]=pool[Math.floor(rng()*pool.length)]}return {a,b,ans:a*b,key:a+'x'+b}}
function distract(ans,rng){const ds=[-10,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,10];let d=ans+ds[Math.floor(rng()*ds.length)];if(d<=0||d===ans)d=ans+1+Math.floor(rng()*5);return d}
function randTheme(rng){return Object.keys(THEMES)[Math.floor(rng()*4)]}
function resizeCanvas(){if(!canvas)return;const r=canvas.getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);W=Math.max(320,r.width);H=Math.max(220,r.height);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function startGame(){if(!data.nickname){openSetup();return}ensureDaily();stopGame();const seed=pendingChallenge?pendingChallenge.s:Math.floor(Math.random()*2147483647),rng=seedRand(seed),duration=TEST?32:300,theme=randTheme(rng);game={seed,rng,duration,time:duration,elapsed:0,theme,score:0,combo:0,bestCombo:0,soldiers:5,power:1,base:100,energy:0,answers:0,correct:0,bossDamage:0,bossMax:1,boss:null,bossStarted:false,bossPhase:0,enemies:[],shots:[],particles:[],floats:[],supply:null,nextQ:TEST?3:16+rng()*5,q:null,questionOpen:false,revive:true,shieldUntil:0,focusId:null,spawnTimer:0,shotTimer:0,supplyTimer:TEST?6:20+rng()*12,shake:0,target:pendingChallenge?.score??null,targetName:pendingChallenge?.n??null,ended:false,lastSkillReady:false};$('#battleWrap').dataset.theme=theme;$('#stageName').textContent=THEMES[theme].name;$('#bossBar').classList.add('hidden');$('#bossWarning').classList.add('hidden');$('#questionPanel').classList.add('hidden');$('#shareArea').classList.add('hidden');showScreen('game');resizeCanvas();startMusic();sfx('start');toast('⚔️ '+THEMES[theme].name);lastTs=performance.now();raf=requestAnimationFrame(loop)}
function stopGame(){if(raf)cancelAnimationFrame(raf);raf=0;if(game)game.ended=true;stopMusic()}
function loop(ts){if(!game||game.ended)return;const dt=Math.min(.05,(ts-lastTs)/1000||0);lastTs=ts;tick(dt);draw();renderHud();raf=requestAnimationFrame(loop)}
function tick(dt){game.time-=dt;game.elapsed+=dt;if(game.time<=0){endGame();return}const p=1-game.time/game.duration,slow=game.questionOpen?.38:1;game.spawnTimer+=dt;if(game.spawnTimer>(TEST?.7:Math.max(.72,1.55-p*.55))){game.spawnTimer=0;spawnEnemy(false)}if(!game.bossStarted&&p>.70){startBoss()}game.shotTimer+=dt;if(game.shotTimer>(TEST?.24:.42)){game.shotTimer=0;autoFire()}game.supplyTimer-=dt;if(game.supplyTimer<=0&&!game.supply){spawnSupply();game.supplyTimer=TEST?8:24+game.rng()*16}for(const e of [...game.enemies]){if(e.dead)continue;if(!e.boss){const speed=e.speed*slow*(e.rush||1);e.x-=speed*dt;e.rush=Math.max(1,(e.rush||1)-dt*1.4);if(e.x<95){const shield=performance.now()<game.shieldUntil;damageBase(e.damage*(shield?.2:1));killEnemy(e,false);continue}}if(e.hitFlash>0)e.hitFlash-=dt;if(e.boss)e.wobble=(e.wobble||0)+dt}for(const s of [...game.shots]){s.t+=dt;const dur=s.dur||.28;const q=Math.min(1,s.t/dur);s.x=s.x0+(s.x1-s.x0)*q;s.y=s.y0+(s.y1-s.y0)*q;if(q>=1){hitTarget(s.target,s.damage,s.kind);game.shots.splice(game.shots.indexOf(s),1)}}for(const p of [...game.particles]){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=70*dt;if(p.life<=0)game.particles.splice(game.particles.indexOf(p),1)}for(const f of [...game.floats]){f.life-=dt;f.y-=25*dt;if(f.life<=0)game.floats.splice(game.floats.indexOf(f),1)}if(game.supply){game.supply.bob+=dt;if(game.elapsed-game.supply.spawned>8){game.supply=null;$('#supplyHint').classList.add('hidden')}}game.nextQ-=dt;if(game.nextQ<=0&&!game.questionOpen){openQuestion();game.nextQ=TEST?5:20+game.rng()*10}updateBossPhase();updateSkillButtons()}
function spawnEnemy(forceLarge=false,fromBoss=false){if(!game||game.ended)return;const p=game.elapsed/game.duration,r=game.rng(),type=forceLarge?'large':r<.52?'small':r<.82?'mid':'large',base={small:14,mid:28,large:52}[type],hp=Math.round(base*(1+p*1.5)),lane=Math.floor(game.rng()*3),y=laneY(lane),x=W+50+game.rng()*50,e={id:entityId++,type,hp,max:hp,damage:{small:4,mid:7,large:11}[type],speed:(TEST?150:47+p*18)*(fromBoss?1.1:1),x,y,boss:false,dead:false,hitFlash:0,rush:1,scale:{small:.75,mid:1,large:1.22}[type],lane};game.enemies.push(e);return e}
function startBoss(){game.bossStarted=true;data.daily.boss=true;save();$('#bossWarning').classList.remove('hidden');sfx('boss');bossMusic(true);setTimeout(()=>{$('#bossWarning').classList.add('hidden');if(!game||game.ended)return;const hp=TEST?150:700+Math.round(game.elapsed*1.7),e={id:entityId++,type:'boss',hp,max:hp,damage:0,speed:0,x:W-135,y:laneY(1)-20,boss:true,dead:false,hitFlash:0,wobble:0,shield:true,scale:1.55,lane:1};game.boss=e;game.bossMax=hp;game.enemies.push(e);game.bossPhase=1;$('#bossBar').classList.remove('hidden');$('#bossShieldBadge').classList.remove('hidden');$('#bossPhaseText').textContent='PHASE 1';game.nextQ=Math.min(game.nextQ,2.5);for(let i=0;i<3;i++)spawnEnemy(i===2,true)},TEST?350:1400)}
function updateBossPhase(){const b=game.boss;if(!b||b.dead)return;const ratio=b.hp/b.max;let phase=ratio>.66?1:ratio>.33?2:3;if(phase>game.bossPhase){game.bossPhase=phase;b.shield=true;$('#bossShieldBadge').classList.remove('hidden');$('#bossPhaseText').textContent='PHASE '+phase;toast('👹 '+t('bossPhase')+' '+phase);sfx('boss');for(let i=0;i<phase+2;i++)spawnEnemy(i===phase+1,true);game.nextQ=Math.min(game.nextQ,1.5);if(phase===3){for(const e of game.enemies)if(!e.boss)e.rush=1.8}}$('#bossHpFill').style.width=Math.max(0,ratio*100)+'%'}
function laneY(l){const groundTop=H*.58,step=(H*.37)/3;return groundTop+step*(l+.55)}
function damageBase(d){game.base=Math.max(0,game.base-d);game.shake=Math.max(game.shake,8);flash('bad');sfx('hurt');addFloat(90,H*.72,'-'+Math.round(d)+' HP','#ff6681');if(game.base<=0){if(game.revive){game.revive=false;game.base=45;game.energy=Math.max(game.energy,30);toast('💚 FREE REVIVE!');burst(90,H*.68,22,'#6ff3b5')}else endGame()}}
function autoFire(){if(!game.enemies.length)return;const focused=game.enemies.find(e=>e.id===game.focusId&&!e.dead),target=focused||game.enemies.filter(e=>!e.dead).sort((a,b)=>(a.boss?1:0)-(b.boss?1:0)||a.x-b.x)[0];if(!target)return;const count=Math.min(6,Math.max(1,Math.ceil(game.soldiers/3)));for(let i=0;i<count;i++){const sx=128+(i%3)*12,sy=laneY(i%3)-18-(Math.floor(i/3)*10),dmg=Math.max(1,Math.round((game.soldiers/count)*game.power*(.42+game.rng()*.18)));game.shots.push({x0:sx,y0:sy,x:sx,y:sy,x1:target.x,y1:target.y-18,t:0,dur:.22+game.rng()*.12,damage:dmg,target,kind:'normal'});setTimeout(()=>sfx('shot'),i*30)}}
function hitTarget(e,dmg,kind='normal'){if(!game||!e||e.dead)return;let actual=dmg;if(e.boss&&e.shield&&kind!=='bomb')actual*=.15;e.hp-=actual;e.hitFlash=.09;if(e.boss)game.bossDamage+=actual;burst(e.x,e.y-15,kind==='bomb'?18:5,kind==='bomb'?'#ffd75c':'#fff1a0');if(kind==='power')addFloat(e.x,e.y-45,'CRIT '+Math.round(actual)+'!','#ffe565');if(e.hp<=0)killEnemy(e,true)}
function killEnemy(e,reward){if(e.dead)return;e.dead=true;if(reward){const pts=e.boss?1600:{small:35,mid:65,large:110}[e.type];game.score+=pts;addFloat(e.x,e.y-35,'+'+pts,'#ffe66d');burst(e.x,e.y,22,e.boss?'#ff5a7b':THEMES[game.theme].accent);sfx(e.boss?'bossDown':'boom')}if(e.boss){game.boss=null;$('#bossBar').classList.add('hidden');toast('🏆 '+t('bossDown'));bossMusic(false);game.energy=Math.min(100,game.energy+35);game.power+=.35}else if(game.focusId===e.id)game.focusId=null;setTimeout(()=>{if(game)game.enemies=game.enemies.filter(x=>!x.dead)},80)}
function burst(x,y,n,color){if(!game)return;for(let i=0;i<n;i++){const a=game.rng()*Math.PI*2,sp=35+game.rng()*130;game.particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-30,life:.35+game.rng()*.55,max:.9,color,size:2+game.rng()*5})}}
function addFloat(x,y,text,color){game.floats.push({x,y,text,color,life:1.05})}
function spawnSupply(){if(!game)return;game.supply={x:W*(.42+game.rng()*.28),y:laneY(Math.floor(game.rng()*3))-28,bob:0,spawned:game.elapsed};$('#supplyHint').classList.remove('hidden');sfx('supply')}
function collectSupply(){if(!game?.supply)return;const s=game.supply,bonus=18+Math.floor(game.rng()*13);game.energy=Math.min(100,game.energy+bonus);game.score+=75;burst(s.x,s.y,16,'#ffe977');addFloat(s.x,s.y-20,'+'+bonus+'⚡','#ffe977');game.supply=null;$('#supplyHint').classList.add('hidden');toast('📦 '+t('supply')+' +'+bonus+'⚡');sfx('correct')}
function useSkill(kind){if(!game||game.ended)return;const cfg={shot:{cost:25},shield:{cost:35},bomb:{cost:60}}[kind];if(game.energy<cfg.cost){toast('⚡ '+t('notEnough'));sfx('no');return}game.energy-=cfg.cost;if(kind==='shot'){const target=game.enemies.find(e=>e.id===game.focusId&&!e.dead)||game.enemies.filter(e=>!e.dead).sort((a,b)=>a.x-b.x)[0];if(target){game.shots.push({x0:95,y0:H*.49,x:95,y:H*.49,x1:target.x,y1:target.y-20,t:0,dur:.35,damage:85+game.power*18,target,kind:'power'});game.shake=5;flash('good');sfx('power')}}else if(kind==='shield'){game.shieldUntil=performance.now()+8000;flash('good');burst(90,H*.67,20,'#74c7ff');toast('🛡️ 8s SHIELD');sfx('shield')}else{flash('bomb');game.shake=14;sfx('bomb');for(const e of game.enemies.filter(e=>!e.dead))hitTarget(e,55+game.power*10,'bomb');for(let i=0;i<5;i++)setTimeout(()=>burst(W*(.35+i*.11),H*(.45+game.rng()*.35),28,'#ffb14e'),i*70)}updateSkillButtons()}
function updateSkillButtons(){if(!game)return;for(const [id,cost] of [['#skillShot',25],['#skillShield',35],['#skillBomb',60]]){const b=$(id);b.disabled=game.energy<cost;b.classList.toggle('ready',game.energy>=cost)}if(game.energy>=60&&!game.lastSkillReady){game.lastSkillReady=true;toast('⚡ '+t('skillReady'))}if(game.energy<45)game.lastSkillReady=false}
function openQuestion(forced=false){if(!game||game.questionOpen)return;const f=weightedFact(game.rng),modes=['lane','monster','bridge','balloon'];if(game.elapsed/game.duration>.25)modes.push('keypad');if(game.elapsed/game.duration>.4)modes.push('inverse');const mode=modes[Math.floor(game.rng()*modes.length)];game.q={...f,mode,forced};game.questionOpen=true;renderQuestion()}
function renderQuestion(){const q=game.q,p=$('#questionPanel');let ans=q.ans,eq=`${q.a} × ${q.b} = ?`;if(q.mode==='inverse'){ans=q.a;eq=`? × ${q.b} = ${q.ans}`}q.displayAns=ans;const wrong=distract(ans,game.rng),pair=game.rng()<.5?[ans,wrong]:[wrong,ans],labels={lane:t('lane'),monster:t('monster'),bridge:t('bridge'),balloon:t('balloon'),inverse:t('inverse')};if(q.mode==='keypad'){p.innerHTML=`<div class="qTop"><span class="qLabel">${esc(t('type'))}</span><span class="slowBadge">⏳ ${esc(t('slow'))}</span></div><div class="equation">${eq}</div><div id="keyDisplay" class="keyDisplay">_</div><div class="keypad">${[1,2,3,4,5,6,7,8,9,0].map(n=>`<button class="key" data-key="${n}">${n}</button>`).join('')}</div><div class="keyActions"><button id="keyBack" class="btn">⌫</button><button id="keyGo" class="btn">OK</button></div>`;let buf='';p.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{if(buf.length<3){buf+=b.dataset.key;$('#keyDisplay').textContent=buf}}));$('#keyBack').onclick=()=>{buf=buf.slice(0,-1);$('#keyDisplay').textContent=buf||'_'};$('#keyGo').onclick=()=>submitAnswer(Number(buf),$('#keyGo'))}else{const icon={lane:['🛣️','🛣️'],monster:['👾','👹'],bridge:['🪨','🪵'],balloon:['🎈','🎈'],inverse:['🔢','🔢']}[q.mode];p.innerHTML=`<div class="qTop"><span class="qLabel">${esc(labels[q.mode]||t('inverse'))}</span><span class="slowBadge">⏳ ${esc(t('slow'))}</span></div><div class="equation">${eq}</div><div class="answers">${pair.map((v,i)=>`<button class="answerBtn ${q.mode}" data-answer="${v}"><span class="answerIcon">${icon[i]}</span>${v}</button>`).join('')}</div>`;p.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>submitAnswer(Number(b.dataset.answer),b)))}p.classList.remove('hidden')}
function submitAnswer(v,btn){if(!game||!game.questionOpen)return;const q=game.q,ok=v===q.displayAns;game.answers++;data.answered++;data.daily.answers++;if(ok){game.correct++;data.correct++;game.combo++;game.bestCombo=Math.max(game.bestCombo,game.combo);data.daily.maxCombo=Math.max(data.daily.maxCombo,game.combo);data.weak[q.key]=Math.max(0,(data.weak[q.key]||0)-1);const add=2+Math.floor(game.combo/4),energy=24+Math.min(16,game.combo*2);game.soldiers=Math.min(30,game.soldiers+add);game.energy=Math.min(100,game.energy+energy);game.power=Math.min(4.5,game.power+(game.combo%4===0?.18:.04));game.score+=140+game.combo*22;if(game.boss?.shield){game.boss.shield=false;$('#bossShieldBadge').classList.add('hidden');toast('🛡️ '+t('bossShield'));for(let i=0;i<Math.min(8,game.soldiers);i++)setTimeout(autoFire,i*45)}else toast('✅ '+t('correct')+' '+t('armyPlus')+add+' · '+t('energyPlus')+energy);flash('good');comboPop(game.combo);burst(W*.5,H*.42,20,'#62efaa');sfx('correct');if(btn)btn.classList.add('good')}else{game.combo=0;data.weak[q.key]=Math.min(9,(data.weak[q.key]||0)+3);game.energy=Math.max(0,game.energy-10);game.score=Math.max(0,game.score-30);for(const e of game.enemies)if(!e.boss)e.rush=2.2;flash('bad');game.shake=8;toast('💡 '+t('answerWas')+' '+q.displayAns+' · 👾 RUSH!');sfx('wrong');if(btn)btn.classList.add('bad')}save();setTimeout(()=>{if(game&&!game.ended){pclose();}},ok?650:1150)}
function pclose(){$('#questionPanel').classList.add('hidden');if(game)game.questionOpen=false}
function comboPop(n){const el=$('#comboPop');el.textContent=n>=2?'🔥 '+n+' COMBO!':'✨ '+t('correct');el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function flash(kind){const e=$('#screenFlash');e.className='screenFlash '+kind;setTimeout(()=>{if(e.className.includes(kind))e.className='screenFlash'},650)}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1500)}
function renderHud(){if(!game)return;$('#baseHp').textContent=Math.round(game.base);$('#soldierCount').textContent=game.soldiers;$('#combo').textContent=game.combo;$('#score').textContent=Math.round(game.score);$('#energyFill').style.width=game.energy+'%';$('#energyText').textContent=Math.round(game.energy);const s=Math.max(0,Math.ceil(game.time));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('#timeBar').style.width=(100-game.time/game.duration*100)+'%'}
function draw(){ctx.clearRect(0,0,W,H);const sh=game.shake>0?(game.shake*=.82):0;ctx.save();if(sh>1)ctx.translate((game.rng()-.5)*sh,(game.rng()-.5)*sh);drawStage();drawBase();drawSoldiers();if(game.supply)drawSupply();for(const e of game.enemies)if(!e.dead)drawEnemy(e);for(const s of game.shots)drawShot(s);for(const p of game.particles)drawParticle(p);for(const f of game.floats)drawFloat(f);if(performance.now()<game.shieldUntil)drawShield();ctx.restore()}
function drawStage(){const th=THEMES[game.theme],g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,th.sky1);g.addColorStop(.58,th.sky2);g.addColorStop(.581,th.ground);g.addColorStop(1,th.ground2);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(game.theme==='meadow'){ctx.fillStyle='rgba(46,132,70,.45)';for(let x=-80;x<W+100;x+=150){ctx.beginPath();ctx.arc(x,H*.6,120,Math.PI,0);ctx.fill()}}else if(game.theme==='desert'){ctx.fillStyle='rgba(255,233,190,.34)';for(let x=-80;x<W+120;x+=190){ctx.beginPath();ctx.ellipse(x,H*.64,150,42,0,Math.PI,0);ctx.fill()}}else if(game.theme==='ice'){ctx.fillStyle='rgba(255,255,255,.5)';for(let x=20;x<W;x+=160){ctx.beginPath();ctx.moveTo(x,H*.58);ctx.lineTo(x+55,H*.22);ctx.lineTo(x+110,H*.58);ctx.fill()};for(let i=0;i<26;i++){const x=(i*83+game.elapsed*9)%W,y=(i*47+game.elapsed*14)%H*.55;ctx.fillRect(x,y,2,2)}}else{ctx.fillStyle='rgba(255,100,50,.2)';for(let x=0;x<W;x+=95){ctx.beginPath();ctx.arc(x,H*.8,32,0,Math.PI*2);ctx.fill()};for(let i=0;i<16;i++){const x=(i*117+game.elapsed*20)%W,y=H*.7-((i*35+game.elapsed*30)%120);ctx.fillStyle='rgba(255,183,77,.45)';ctx.fillRect(x,y,3,3)}}ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=1;for(let l=0;l<3;l++){ctx.beginPath();ctx.moveTo(0,laneY(l)+28);ctx.lineTo(W,laneY(l)+28);ctx.stroke()}}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke()}}
function drawBase(){roundRect(24,H*.48,78,H*.38,14,'#5b69bd','#b7c2ff');ctx.fillStyle='#27356f';ctx.fillRect(37,H*.58,52,H*.28);ctx.fillStyle='#fff';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.fillText('BASE',63,H*.82);ctx.fillStyle='#ff637c';ctx.fillRect(28,H*.45,70,7);ctx.fillStyle='#72e5a7';ctx.fillRect(28,H*.45,70*(game.base/100),7)}
function drawSoldiers(){const n=Math.min(10,game.soldiers),bob=Math.sin(game.elapsed*7)*2;for(let i=0;i<n;i++){const lane=i%3,row=Math.floor(i/3),x=122+row*20,y=laneY(lane)+bob-(row%2)*5;ctx.save();ctx.translate(x,y);ctx.fillStyle='#394c7a';ctx.fillRect(-5,-13,11,17);ctx.fillStyle='#f2c9a7';ctx.beginPath();ctx.arc(0,-17,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5c7741';ctx.beginPath();ctx.arc(0,-21,8,Math.PI,0);ctx.fill();ctx.strokeStyle='#27351f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(5,-10);ctx.lineTo(15,-13);ctx.stroke();ctx.restore()}}
function drawEnemy(e){const th=THEMES[game.theme],c=e.boss?'#c83a61':th.enemy[e.type==='small'?0:e.type==='mid'?1:2],r=(e.boss?38:e.type==='large'?26:e.type==='mid'?22:18)*e.scale;ctx.save();ctx.translate(e.x,e.y+(e.boss?Math.sin(e.wobble*3)*4:Math.sin(game.elapsed*5+e.id)*2));if(e.hitFlash>0)ctx.globalAlpha=.45;ctx.fillStyle=c;ctx.beginPath();ctx.arc(0,-r*.45,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.28)';ctx.beginPath();ctx.ellipse(-r*.28,-r*.8,r*.32,r*.22,-.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-r*.28,-r*.55,r*.18,0,Math.PI*2);ctx.arc(r*.28,-r*.55,r*.18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#182038';ctx.beginPath();ctx.arc(-r*.24,-r*.52,r*.08,0,Math.PI*2);ctx.arc(r*.24,-r*.52,r*.08,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#40223b';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-r*.25,r*.32,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.fillStyle='#2a1630';ctx.fillRect(-r,-r*1.65,r*2,6);ctx.fillStyle=e.shield?'#6cc9ff':'#76ed9d';ctx.fillRect(-r,-r*1.65,r*2*Math.max(0,e.hp/e.max),6);if(e.id===game.focusId){ctx.strokeStyle='#ffe66e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-r*.45,r+7,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffe66e';ctx.font='900 10px system-ui';ctx.textAlign='center';ctx.fillText(t('target'),0,r*.85)}if(e.boss&&e.shield){ctx.strokeStyle='rgba(95,196,255,.85)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-r*.45,r+12,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawShot(s){ctx.save();ctx.shadowBlur=12;ctx.shadowColor=s.kind==='power'?'#fff46d':'#f5e55a';ctx.fillStyle=s.kind==='power'?'#fff9b0':'#ffe45f';ctx.beginPath();ctx.arc(s.x,s.y,s.kind==='power'?8:3.5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawParticle(p){ctx.save();ctx.globalAlpha=Math.max(0,p.life/.9);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);ctx.restore()}
function drawFloat(f){ctx.save();ctx.globalAlpha=Math.min(1,f.life);ctx.font='1000 16px system-ui';ctx.textAlign='center';ctx.fillStyle=f.color;ctx.strokeStyle='rgba(0,0,0,.35)';ctx.lineWidth=4;ctx.strokeText(f.text,f.x,f.y);ctx.fillText(f.text,f.x,f.y);ctx.restore()}
function drawSupply(){const s=game.supply,y=s.y+Math.sin(s.bob*4)*5;ctx.save();ctx.translate(s.x,y);ctx.shadowBlur=18;ctx.shadowColor='#ffe26a';roundRect(-22,-22,44,38,8,'#ffd45f','#7b5d1d');ctx.fillStyle='#8b6925';ctx.fillRect(-22,-6,44,7);ctx.fillStyle='#fff4b2';ctx.font='900 15px system-ui';ctx.textAlign='center';ctx.fillText('⚡',0,3);ctx.restore()}
function drawShield(){ctx.save();ctx.strokeStyle='rgba(93,205,255,.8)';ctx.lineWidth=6;ctx.shadowBlur=18;ctx.shadowColor='#6bd6ff';ctx.beginPath();ctx.ellipse(67,H*.66,64,102,0,0,Math.PI*2);ctx.stroke();ctx.restore()}
function pointerBattle(ev){if(!game||game.ended)return;const r=canvas.getBoundingClientRect(),x=(ev.clientX-r.left)*(W/r.width),y=(ev.clientY-r.top)*(H/r.height);if(game.supply&&Math.hypot(x-game.supply.x,y-game.supply.y)<48){collectSupply();return}const hit=[...game.enemies].filter(e=>!e.dead).reverse().find(e=>Math.hypot(x-e.x,y-e.y)<(e.boss?70:e.type==='large'?48:40));if(hit){game.focusId=hit.id;burst(hit.x,hit.y-20,8,'#ffe66d');sfx('target')}}
function endGame(){if(!game||game.ended)return;game.ended=true;if(raf)cancelAnimationFrame(raf);raf=0;stopMusic();const acc=game.answers?game.correct/game.answers:0,coins=Math.max(8,Math.round(game.score/150)+game.correct*2),xpGain=Math.round(game.score/18)+game.correct*6,loot=['✨ Star Sticker','🐾 Pet Shard','🎨 Skin Ticket','⚡ Power Badge'][Math.floor(game.rng()*4)];data.coins+=coins;data.xp+=xpGain;data.loot=(data.loot||0)+1;updateStreak();save();lastResult={seed:game.seed,score:Math.round(game.score),acc:Math.round(acc*100),combo:game.bestCombo,coins,xp:xpGain,boss:Math.min(game.bossMax||1,game.bossDamage),bossMax:game.bossMax||1,target:game.target,targetName:game.targetName,loot};$('#resultScore').textContent=lastResult.score.toLocaleString();$('#resultAcc').textContent=lastResult.acc+'%';$('#resultCombo').textContent=lastResult.combo;$('#resultCoins').textContent='+'+coins;$('#resultBoss').textContent=Math.round(lastResult.boss/lastResult.bossMax*100)+'%';$('#xpGain').textContent='+'+xpGain;$('#resultTitle').textContent=acc>=.72?t('great'):t('practice');$('#lootReward').textContent='🎁 '+t('loot')+': '+loot;$('#challengeBeat').textContent=lastResult.target!=null?((lastResult.score>lastResult.target?'🏆 ':'🎯 ')+lastResult.targetName+' · '+lastResult.target):'';$('#xpFill').style.width='0%';showScreen('result');setTimeout(()=>{$('#xpFill').style.width=Math.min(100,(xpGain%100))+'%';openLoot()},250);if(pendingChallenge){data.board=dedupeBoard([{n:data.nickname,score:lastResult.score,acc:lastResult.acc,ts:Date.now()},...data.board]);save()}pendingChallenge=null}
function openLoot(){const c=$('#lootChest');c.classList.add('open');const rain=$('#coinRain');rain.innerHTML='';for(let i=0;i<12;i++){const s=document.createElement('span');s.className='coinDrop';s.textContent='🪙';s.style.left=(8+Math.random()*84)+'%';s.style.animationDelay=(Math.random()*.45)+'s';rain.appendChild(s)}sfx('loot')}
function updateStreak(){const d=today();if(data.lastDay===d)return;const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);data.streak=data.lastDay===prev?data.streak+1:1;data.lastDay=d}
function b64e(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64d(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return decodeURIComponent(escape(atob(s)))}
function makeCode(){if(!lastResult)return'';return b64e(JSON.stringify({v:2,n:data.nickname.slice(0,16),s:lastResult.seed,score:lastResult.score,acc:lastResult.acc}))}
function parseCode(code){try{const clean=String(code).trim().replace(/^.*[?&]c=/,'').split('&')[0],o=JSON.parse(b64d(clean));if(![1,2].includes(o.v)||!o.n||!Number.isFinite(o.s)||!Number.isFinite(o.score))throw 0;return o}catch(e){return null}}
function loadChallenge(raw,board=false){const o=parseCode(raw);if(!o){toast(t('invalidCode'));return false}if(board){data.board=dedupeBoard([{n:o.n,score:o.score,acc:o.acc||0,ts:Date.now()},...data.board]);save();renderBoard();toast(t('imported'))}else{pendingChallenge=o;toast('🎯 '+t('challengeLoaded')+': '+o.n);setTimeout(startGame,450)}return true}
function dedupeBoard(a){const seen=new Set();return a.filter(x=>{const k=x.n+'|'+x.score;if(seen.has(k))return false;seen.add(k);return true}).slice(0,30)}
function makeShare(){const code=makeCode(),url=location.origin+location.pathname+'?c='+encodeURIComponent(code);$('#shareCode').textContent=code;$('#shareArea').classList.remove('hidden');$('#shareBtn').dataset.url=url;setTimeout(()=>{try{if(window.QRious)new QRious({element:$('#qr'),value:url,size:144,level:'M'});else{const c=$('#qr').getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,144,144);c.fillStyle='#111';c.font='12px system-ui';c.fillText('Share code above',20,72)}}catch(e){}},30)}
async function share(){const code=makeCode(),url=$('#shareBtn').dataset.url||location.href,text=`Times Table Arena\n${data.nickname}: ${lastResult.score} pts\n${code}`;try{if(navigator.share)await navigator.share({title:'Times Table Arena',text,url});else prompt('Copy challenge code:',code)}catch(e){}}
function renderCollection(){const av=[['🧑‍🚀',0],['🥷',80],['🧙',160],['🦸',260],['🤖',400],['🐉',650]],pets=[['',0,'—'],['🐶',180,'🐶'],['🐱',300,'🐱'],['🦊',520,'🦊']];$('#avatars').innerHTML=av.map(([x,c])=>item('avatar',x,c,data.avatar===x)).join('');$('#pets').innerHTML=pets.map(([x,c,l])=>item('pet',l,c,data.pet===x,x)).join('');$$('[data-collect]').forEach(b=>b.onclick=()=>selectCollect(b))}
function item(type,label,c,sel,val=label){const locked=data.coins<c;return `<button class="collectItem ${sel?'selected':''} ${locked?'locked':''}" data-collect="${type}" data-value="${esc(val)}" data-cost="${c}"><div class="big">${label}</div><b>${sel?t('selected'):locked?t('need')+' '+c+' 🪙':t('unlocked')}</b></button>`}
function selectCollect(b){const c=Number(b.dataset.cost);if(data.coins<c){toast(t('need')+' '+c+' 🪙');return}data[b.dataset.collect]=b.dataset.value;save();renderCollection();renderLobby()}
function renderProgress(){const acc=data.answered?Math.round(data.correct/data.answered*100):0;$('#lifeAcc').textContent=data.answered?acc+'%':'—';$('#lifeAnswered').textContent=data.answered;const a=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const k=i+'x'+j,w=data.weak[k]||0;if(w>0)a.push([k,w])}a.sort((x,y)=>y[1]-x[1]);$('#weakGrid').innerHTML=a.length?a.slice(0,16).map(([k,w])=>`<div class="weak"><b>${k.replace('x','×')}</b><div>${'⭐'.repeat(Math.min(3,Math.ceil(w/3)))}</div></div>`).join(''):'<div class="muted">No weak facts yet — play a round!</div>'}
function renderBoard(){const a=[...data.board].sort((x,y)=>y.score-x.score);$('#boardList').innerHTML=a.length?a.map((x,i)=>`<div class="boardRow"><div class="rank">#${i+1}</div><div class="grow"><b>${esc(x.n)}</b><div class="muted">${x.acc||0}% accuracy</div></div><b>${Number(x.score).toLocaleString()}</b></div>`).join(''):`<div class="panel muted" style="padding:14px">${t('noBoard')}</div>`}
function audioCtx(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}catch(e){return null}}
function tone(freq,dur=.09,vol=.035,type='sine',delay=0){if(!data.music)return;const a=audioCtx();if(!a)return;const o=a.createOscillator(),g=a.createGain(),st=a.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,st);g.gain.setValueAtTime(vol,st);g.gain.exponentialRampToValueAtTime(.001,st+dur);o.connect(g).connect(a.destination);o.start(st);o.stop(st+dur+.02)}
function sfx(k){const m={start:[[392,.08],[523,.1]],shot:[[660,.04,.018]],target:[[520,.05,.02]],boom:[[110,.13,.05,'square']],boss:[[130,.2,.05,'sawtooth'],[98,.25,.05,'sawtooth']],bossDown:[[392,.1],[523,.1],[659,.18]],correct:[[523,.07],[659,.07],[784,.12]],wrong:[[190,.12,.05,'square'],[145,.14,.04,'square']],hurt:[[110,.08,.04,'square']],supply:[[700,.07],[900,.1]],power:[[850,.08],[1200,.12]],shield:[[440,.12],[660,.18]],bomb:[[90,.28,.07,'sawtooth']],loot:[[659,.08],[784,.08],[988,.18]],no:[[150,.08,.02]]}[k]||[];m.forEach((n,i)=>tone(n[0],n[1],n[2]??.035,n[3]||'sine',i*.055))}
function startMusic(){if(!data.music)return;const a=audioCtx();if(!a)return;clearInterval(musicTimer);let n=0;musicTimer=setInterval(()=>{if(!game||game.ended||!data.music)return;const boss=!!game.boss,notes=boss?[220,261.6,196,293.7,220,329.6]:[261.6,329.6,392,329.6,293.7,349.2,440,349.2];tone(notes[n++%notes.length],.13,boss?.022:.017,'triangle')},game?.boss?230:360)}
function bossMusic(on){if(!game||!data.music)return;startMusic()}
function stopMusic(){clearInterval(musicTimer);musicTimer=0}
function toggleMusic(){data.music=!data.music;save();$('#musicBtn').textContent=data.music?'🔊':'🔇';if(data.music&&game&&!game.ended)startMusic();else stopMusic()}
function updateSkillLabels(){/* i18n handled by data-i18n */}
canvas=$('#battleCanvas');ctx=canvas.getContext('2d');canvas.addEventListener('pointerdown',pointerBattle);
$('#skillShot').onclick=()=>useSkill('shot');$('#skillShield').onclick=()=>useSkill('shield');$('#skillBomb').onclick=()=>useSkill('bomb');
$('#langBtn').onclick=()=>{data.lang=data.lang==='en'?'zh':'en';save();applyLang()};$('#musicBtn').onclick=toggleMusic;$('#playBtn').onclick=()=>{pendingChallenge=null;startGame()};$('#settingsBtn').onclick=openSetup;$('#setupForm').addEventListener('submit',e=>{e.preventDefault();const n=$('#nicknameInput').value.trim().replace(/[^\p{L}\p{N}_\- ]/gu,'').slice(0,16);if(!n)return;data.nickname=n;data.focus=$('#focusSelect').value;save();$('#setupModal').classList.add('hidden');renderLobby()});$$('[data-open]').forEach(b=>b.onclick=()=>showScreen(b.dataset.open));$$('.backBtn').forEach(b=>b.onclick=()=>showScreen('lobby'));$('#loadChallengeBtn').onclick=()=>loadChallenge($('#challengeInput').value);$('#importBoardBtn').onclick=()=>loadChallenge($('#boardCode').value,true);$('#retryBtn').onclick=()=>startGame();$('#homeBtn').onclick=()=>showScreen('lobby');$('#makeChallengeBtn').onclick=makeShare;$('#shareBtn').onclick=share;$('#dismissRotate').onclick=()=>{rotateDismissed=true;$('#rotatePrompt').classList.add('dismissed','hidden')};addEventListener('resize',()=>{resizeCanvas();checkRotate()});addEventListener('orientationchange',()=>setTimeout(()=>{resizeCanvas();checkRotate()},200));
window.__TTA_V2_TEST__={startGame,openQuestion,submitAnswer,useSkill,startBoss,spawnEnemy,spawnSupply,collectSupply,endGame,getGame:()=>game,getData:()=>data,makeCode,parseCode,forceCorrect(){if(game?.q)submitAnswer(game.q.displayAns,null)},forceWrong(){if(game?.q)submitAnswer(-999,null)},breakBoss(){if(game?.boss){game.boss.shield=false;game.boss.hp=game.boss.max*.3;updateBossPhase()}},finish(){if(game){game.time=.01}}};
ensureDaily();$('#musicBtn').textContent=data.music?'🔊':'🔇';applyLang();if(!data.nickname)openSetup();const incoming=new URLSearchParams(location.search).get('c');if(incoming){$('#challengeInput').value=incoming;const o=parseCode(incoming);if(o){pendingChallenge=o;toast('🎯 '+t('challengeLoaded')+': '+o.n)}}checkRotate();