'use strict';
const TEST=new URLSearchParams(location.search).get('test')==='1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='tta_v3';
const FRONT_CAP=36;
const defaults={nickname:'',lang:'en',coins:0,xp:0,streak:0,lastDay:'',avatar:'🎤',pet:'',music:true,focus:'auto',answered:0,correct:0,weak:{},board:[],daily:{day:'',answers:0,maxCombo:0,boss:false}};
let data=load(),game=null,raf=0,lastTs=0,ctx=null,C=null,dpr=1,audio=null,musicTimer=0,lastResult=null,pendingChallenge=null,rotateDismissed=false;
const THEMES=[
 {id:'city',name:'NEON CITY ARENA',sky1:'#16134a',sky2:'#40175a',ground:'#15132c',accent:'#55eaff',accent2:'#ff53c8'},
 {id:'shrine',name:'MOONLIGHT SHRINE',sky1:'#111b52',sky2:'#2c1752',ground:'#171526',accent:'#ff8edb',accent2:'#74caff'},
 {id:'ice',name:'ICE STAR STAGE',sky1:'#102a59',sky2:'#284777',ground:'#142e4c',accent:'#9ff8ff',accent2:'#b991ff'},
 {id:'lava',name:'LAVA DEMON DOME',sky1:'#351124',sky2:'#7a251f',ground:'#25131b',accent:'#ffb456',accent2:'#ff4b93'}
];
const I18N={
 en:{welcome:'Welcome back',coins:'Coins',streak:'Streak',battleMode:'NEON IDOL DEFENCE',subtitle:'Defend the stage. Build your squad with maths.',howText:'Fight continuously, focus targets, grab supplies and unleash skills. Correct answers summon exactly that many soldiers; a wrong choice deducts exactly the number you selected.',play:'PLAY BATTLE',load:'Load',collection:'Collection',progress:'My Progress',classboard:'Classboard',settings:'Settings',todayMissions:"Today’s missions",missionA:'Answer 15 facts',missionB:'Reach 5 combo',missionC:'Meet the boss',bossIncoming:'DEMON STAR INCOMING',bossHint:'Keep clearing minions!',tapSupply:'Tap the supply!',powerShot:'Power Shot',shield:'Shield',bomb:'Stage Burst',runComplete:'RUN COMPLETE',accuracy:'Accuracy',bestCombo:'Best combo',coinsEarned:'Coins earned',bossDamage:'Boss damage',finalFrontline:'Final frontline',finalReserve:'Final reserve',retry:'Play again',challengeFriend:'Challenge a friend',home:'Home',share:'Share',collectionHint:'Unlock original Neon Idol Hunter looks with coins. Pet bonuses stay tiny so battles remain fair.',avatars:'Avatars',pets:'Pets',lifetimeAccuracy:'Lifetime accuracy',factsAnswered:'Facts answered',weakFacts:'Facts to practise',boardHint:'No account needed. Import classmates’ challenge codes on this device.',import:'Import',rotate:'Rotate your phone',rotateText:'Battle Arena is designed for landscape mode.',continueAnyway:'Continue anyway',setupTitle:'Player setup',nickname:'Nickname',focus:'Training focus',save:'Save',focusAuto:'Adaptive 1×1–10×10',ready:'Stage ready!',correct:'CORRECT!',wrong:'Not quite',answerWas:'Correct answer:',reinforce:'REINFORCEMENTS!',lost:'SOLDIERS!',rush:'DEMON RUSH!',bossShield:'Boss shield cracked!',bossDown:'DEMON STAR DOWN!',supply:'Supply grabbed!',notEnough:'Not enough energy',great:'Great run!',practice:'Keep building your squad!',shareTitle:'Times Table Arena challenge',shareText:'Can you beat my Times Table Arena score?',challengeLoaded:'Challenge loaded',invalidCode:'Invalid challenge code',imported:'Classmate imported',noBoard:'No classmates imported yet.',beat:'You beat the challenge!',missed:'Target:',unlocked:'Unlocked',need:'Need',selected:'Selected',questionHint:'Battle slows — it does not stop!',type:'Type the answer',inverse:'Find the missing number',choose:'Choose the answer',loot:'Loot unlocked',frontline:'Frontline',reserve:'Reserve'},
 zh:{welcome:'歡迎返嚟',coins:'金幣',streak:'連續日數',battleMode:'NEON IDOL 守衛戰',subtitle:'守住舞台，用乘數召集你嘅戰隊。',howText:'戰鬥會一直進行：鎖定敵人、執補給、使用技能。答啱會增加「答案數字」相同數量嘅士兵；答錯就扣除你所揀答案相同數量嘅士兵。',play:'開始戰鬥',load:'載入',collection:'收藏',progress:'學習進度',classboard:'同學榜',settings:'設定',todayMissions:'今日任務',missionA:'完成 15 題',missionB:'達成 5 Combo',missionC:'見到 Boss',bossIncoming:'DEMON STAR 即將登場',bossHint:'繼續清理小怪！',tapSupply:'撳補給箱！',powerShot:'強力射擊',shield:'護盾',bomb:'舞台爆發',runComplete:'完成一局',accuracy:'正確率',bestCombo:'最高 Combo',coinsEarned:'獲得金幣',bossDamage:'Boss 傷害',finalFrontline:'最後前線',finalReserve:'最後後備',retry:'再玩一次',challengeFriend:'挑戰同學',home:'主頁',share:'分享',collectionHint:'用金幣解鎖原創 Neon Idol Hunter 外觀；寵物能力保持輕微，避免影響公平。',avatars:'角色',pets:'寵物',lifetimeAccuracy:'總正確率',factsAnswered:'已完成題目',weakFacts:'需要多練習',boardHint:'毋須帳戶。將同學 Challenge Code 加入本機即可。',import:'加入',rotate:'請將手機轉為橫向',rotateText:'Battle Arena 為橫向手機畫面設計。',continueAnyway:'照樣繼續',setupTitle:'玩家設定',nickname:'暱稱',focus:'練習重點',save:'儲存',focusAuto:'自動 1×1–10×10',ready:'舞台準備好！',correct:'答啱！',wrong:'差少少',answerWas:'正確答案：',reinforce:'援軍！',lost:'士兵！',rush:'惡魔突進！',bossShield:'Boss 護盾受創！',bossDown:'DEMON STAR 擊倒！',supply:'取得補給！',notEnough:'能量不足',great:'打得好！',practice:'繼續壯大你嘅戰隊！',shareTitle:'Times Table Arena 挑戰',shareText:'你可唔可以打破我嘅 Times Table Arena 分數？',challengeLoaded:'挑戰已載入',invalidCode:'Challenge Code 無效',imported:'已加入同學成績',noBoard:'暫時未加入同學成績。',beat:'你打破咗挑戰！',missed:'目標：',unlocked:'已解鎖',need:'需要',selected:'使用中',questionHint:'戰場會慢動作，但唔會停！',type:'輸入答案',inverse:'找出缺少的數字',choose:'選擇答案',loot:'解鎖獎勵',frontline:'前線',reserve:'後備'}
};
function t(k){return I18N[data.lang]?.[k]||I18N.en[k]||k}
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {...defaults}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}}
function today(){return new Date().toISOString().slice(0,10)}
function ensureDaily(){if(data.daily.day!==today())data.daily={day:today(),answers:0,maxCombo:0,boss:false}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function rand(a,b){return a+Math.random()*(b-a)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function seedRand(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let z=x;z=Math.imul(z^(z>>>15),z|1);z^=z+Math.imul(z^(z>>>7),z|61);return((z^(z>>>14))>>>0)/4294967296}}
function totalTroops(){return game?game.units.length+game.reserve:0}
function applyLang(){document.documentElement.lang=data.lang==='zh'?'zh-Hant':'en';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#langBtn').textContent=data.lang==='en'?'繁中':'EN';$('#challengeInput').placeholder=data.lang==='zh'?'貼上 Challenge Code':'Paste challenge code';$('#boardCode').placeholder=data.lang==='zh'?'貼上同學 Challenge Code':'Paste classmate code';renderLobby()}
function showScreen(id){window.scrollTo(0,0);$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='lobby')renderLobby();if(id==='collection')renderCollection();if(id==='progress')renderProgress();if(id==='board')renderBoard();checkRotate()}
function renderLobby(){ensureDaily();$('#heroAvatar').textContent=data.avatar+(data.pet||'');$('#nickLabel').textContent=data.nickname||'Player';$('#coinsLabel').textContent=data.coins;$('#xpLabel').textContent=data.xp;$('#streakLabel').textContent=data.streak+'🔥';$('#focusLabel').textContent=data.focus==='auto'?t('focusAuto'):'×'+data.focus;const d=data.daily,m=[{n:t('missionA'),v:Math.min(d.answers,15),m:15},{n:t('missionB'),v:Math.min(d.maxCombo,5),m:5},{n:t('missionC'),v:d.boss?1:0,m:1}];$('#missions').innerHTML=m.map(x=>`<div class="mission"><b>${esc(x.n)}</b><div class="muted">${x.v}/${x.m}</div><div class="bar"><i style="width:${x.v/x.m*100}%"></i></div></div>`).join('')}
function openSetup(){$('#nicknameInput').value=data.nickname;$('#focusSelect').value=data.focus;$('#setupModal').classList.remove('hidden')}
function checkRotate(){const portrait=innerHeight>innerWidth&&innerWidth<950,gameish=$('#game').classList.contains('active')||$('#lobby').classList.contains('active');$('#rotatePrompt').classList.toggle('show',gameish&&portrait&&!rotateDismissed)}
function weightedFact(rng){const f=Number(data.focus)||0;let a,b;if(f){a=f;b=1+Math.floor(rng()*10)}else{let pool=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const k=i+'x'+j,w=1+Math.min(6,Number(data.weak[k]||0));for(let n=0;n<w;n++)pool.push([i,j])}[a,b]=pool[Math.floor(rng()*pool.length)]}return{a,b,ans:a*b,key:a+'x'+b}}
function distract(ans,rng){const d=[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,9,10];let x=ans+d[Math.floor(rng()*d.length)];if(x<=0||x===ans)x=ans+1+Math.floor(rng()*6);return x}
function startGame(){if(!data.nickname){openSetup();return}ensureDaily();stopGame();C=$('#battleCanvas');ctx=C.getContext('2d');const seed=pendingChallenge?pendingChallenge.s:Math.floor(Math.random()*2147483647),rng=seedRand(seed),duration=TEST?34:300,theme=THEMES[Math.floor(rng()*THEMES.length)];game={seed,rng,duration,time:duration,elapsed:0,score:0,combo:0,bestCombo:0,base:100,reserve:20,units:[],enemies:[],projectiles:[],particles:[],floaters:[],energy:20,shield:0,focus:null,questionOpen:false,q:null,nextQ:TEST?2.2:12,boss:null,bossStarted:false,bossWarning:false,bossDamage:0,lastSpawn:0,lastDeploy:0,lastSupply:0,supply:null,stage:theme,ended:false,target:pendingChallenge?.score??null,targetName:pendingChallenge?.n??null};for(let i=0;i<18;i++)spawnUnit(true);$('#battleWrap').dataset.theme=theme.id;$('#stageName').textContent=theme.name;$('#bossBar').classList.add('hidden');$('#bossWarning').classList.add('hidden');$('#shareArea').classList.add('hidden');showScreen('game');resizeCanvas();startMusic();toast(t('ready'));lastTs=performance.now();raf=requestAnimationFrame(loop)}
function stopGame(){if(raf)cancelAnimationFrame(raf);raf=0;stopMusic();game=null}
function resizeCanvas(){if(!C)return;const r=$('#battleWrap').getBoundingClientRect();dpr=Math.min(2,window.devicePixelRatio||1);C.width=Math.max(1,Math.round(r.width*dpr));C.height=Math.max(1,Math.round(r.height*dpr));C.style.width=r.width+'px';C.style.height=r.height+'px';ctx?.setTransform(dpr,0,0,dpr,0,0)}
function spawnUnit(initial=false){if(!game||game.units.length>=FRONT_CAP)return false;const types=['blade','blaster','shield','cannon'],i=game.units.length,type=types[i%types.length],u={id:cryptoRand(),type,x:initial?92+(i%12)*12:82,y:0,lane:i%3,hp:type==='shield'?24:16,max:type==='shield'?24:16,cool:rand(0,.8),spawn:initial?1:0,hit:0};game.units.push(u);return true}
function cryptoRand(){return Math.random().toString(36).slice(2)}
function addTroops(n){n=Math.max(0,Math.floor(n));game.reserve=Math.min(9999,game.reserve+n);burstText(`+${n} ${t('reinforce')}`,'#79ffd0');addParticles(96,220,18,'#75ffd0')}
function deductTroops(n){n=Math.max(0,Math.floor(n));const before=totalTroops(),take=Math.min(before,n);let left=take;if(game.reserve>=left){game.reserve-=left;left=0}else{left-=game.reserve;game.reserve=0}while(left>0&&game.units.length){const u=game.units.pop();poofUnit(u);left--}burstText(`-${take} ${t('lost')}`,'#ff7f9b');return take}
function loop(ts){if(!game||game.ended)return;const dt=Math.min(.045,(ts-lastTs)/1000||0);lastTs=ts;update(dt);draw();renderHud();raf=requestAnimationFrame(loop)}
function update(dt){game.time-=dt;game.elapsed+=dt;if(game.time<=0){endGame();return}const progress=1-game.time/game.duration,slow=game.questionOpen?.28:1;
 if(!game.bossStarted&&game.time<=(TEST?12:70)){startBossSequence()}
 game.lastDeploy+=dt;if(game.lastDeploy>.28&&game.reserve>0&&game.units.length<FRONT_CAP){game.lastDeploy=0;const n=Math.min(game.reserve,FRONT_CAP-game.units.length,game.combo>=4?3:2);for(let i=0;i<n;i++){game.reserve--;spawnUnit(false)}}
 game.lastSpawn+=dt;const spawnEvery=TEST?.78:Math.max(1.1,2.45-progress*.9);if(game.lastSpawn>spawnEvery){game.lastSpawn=0;spawnEnemy(progress>.55&&game.rng()<.16?'elite':null)}
 game.lastSupply+=dt;if(!game.supply&&game.lastSupply>(TEST?5:24+game.rng()*14)){game.lastSupply=0;game.supply={x:rand(width()*.46,width()*.73),y:rand(height()*.48,height()*.68),life:9,bob:0};$('#supplyHint').classList.remove('hidden')}
 if(game.supply){game.supply.life-=dt;game.supply.bob+=dt;if(game.supply.life<=0){game.supply=null;$('#supplyHint').classList.add('hidden')}}
 updateUnits(dt,slow);updateEnemies(dt,slow);updateProjectiles(dt);updateParticles(dt);updateFloaters(dt);
 if(game.shield>0)game.shield-=dt;
 game.nextQ-=dt;if(game.nextQ<=0&&!game.questionOpen&&!game.bossWarning){openQuestion();game.nextQ=TEST?4.2:20+game.rng()*10}
}
function updateUnits(dt,slow){const W=width();for(const u of game.units){u.spawn=Math.min(1,u.spawn+dt*3.3);u.hit=Math.max(0,u.hit-dt);const idx=game.units.indexOf(u),tx=108+(idx%12)*15,ty=groundY()-14-(idx%3)*24;u.x+=(tx-u.x)*Math.min(1,dt*4);u.y+=(ty-u.y)*Math.min(1,dt*4);u.cool-=dt*slow;if(u.cool<=0){const target=chooseTarget();if(target){const rate={blade:.55,blaster:.72,shield:.9,cannon:1.25}[u.type];u.cool=rate;const dmg={blade:4.7,blaster:4.1,shield:2.5,cannon:8.5}[u.type]*(1+game.combo*.035);if(u.type==='blade'&&target.x<310){damageEnemy(target,dmg,u.x,u.y);addParticles(target.x,target.y,4,'#ff78ce')}else{game.projectiles.push({x:u.x+12,y:u.y-8,tx:target,spd:u.type==='cannon'?380:520,dmg,type:u.type,life:2})}}}}}
function chooseTarget(){if(game.focus&&game.enemies.includes(game.focus))return game.focus;if(!game.enemies.length)return null;return game.enemies.reduce((a,b)=>a.x<b.x?a:b)}
function updateEnemies(dt,slow){for(const e of [...game.enemies]){e.hit=Math.max(0,e.hit-dt);e.attack-=dt;if(e.dead){e.death+=dt;if(e.death>.35)removeEnemy(e);continue}const frontline=game.units.length>0,stopX=frontline?228:72;if(e.type!=='boss'&&e.x>stopX)e.x-=e.speed*dt*slow*(e.rush||1);else if(e.type==='boss'&&e.x>width()*.72)e.x-=e.speed*dt*slow;
 if(e.x<=stopX+5&&e.attack<=0){e.attack=e.type==='boss'?.85:({imp:1.15,bat:1.25,brute:1.55,wolf:.9}[e.type]||1.1);if(game.units.length){const count=e.type==='boss'?3:1;for(let k=0;k<count&&game.units.length;k++){const i=Math.max(0,game.units.length-1-Math.floor(game.rng()*Math.min(6,game.units.length))),u=game.units[i];u.hp-=e.damage;u.hit=.18;addFloater(u.x,u.y-25,'-'+Math.round(e.damage),'#ff7895');if(u.hp<=0){game.units.splice(i,1);poofUnit(u)}}}else if(game.shield<=0){game.base=Math.max(0,game.base-e.damage*(e.type==='boss'?1.2:1));screenShake();addFloater(76,groundY()-70,'-'+Math.round(e.damage),'#ff7895');if(game.base<=0){game.base=0;endGame();return}}}
 if(e.rush&&e.rush>1){e.rush=Math.max(1,e.rush-dt*1.8)}}}
function updateProjectiles(dt){for(const p of [...game.projectiles]){p.life-=dt;if(p.life<=0||!p.tx||!game.enemies.includes(p.tx)){removeObj(game.projectiles,p);continue}const dx=p.tx.x-p.x,dy=(p.tx.y-8)-p.y,d=Math.hypot(dx,dy)||1,step=p.spd*dt;p.x+=dx/d*step;p.y+=dy/d*step;if(d<16+step){damageEnemy(p.tx,p.dmg,p.x,p.y);addParticles(p.x,p.y,p.type==='cannon'?10:4,p.type==='cannon'?'#ffd36b':'#69eaff');removeObj(game.projectiles,p)}}}
function updateParticles(dt){for(const p of [...game.particles]){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.g*dt;p.a=Math.max(0,p.life/p.max);if(p.life<=0)removeObj(game.particles,p)}}
function updateFloaters(dt){for(const f of [...game.floaters]){f.life-=dt;f.y-=28*dt;if(f.life<=0)removeObj(game.floaters,f)}}
function spawnEnemy(force){if(!game||game.ended)return;const p=game.elapsed/game.duration,r=game.rng();let type=force==='elite'?(r<.5?'brute':'wolf'):(r<.42?'imp':r<.68?'bat':r<.87?'wolf':'brute');const base={imp:15,bat:20,wolf:28,brute:48}[type],hp=base*(1+p*.72),e={id:cryptoRand(),type,x:width()+40,y:groundY()-18-(Math.floor(game.rng()*3)*25),hp,max:hp,speed:{imp:41,bat:52,wolf:62,brute:28}[type],damage:{imp:4,bat:4,wolf:6,brute:9}[type],attack:rand(.2,.8),hit:0,dead:false,death:0,rush:1};game.enemies.push(e)}
function startBossSequence(){game.bossStarted=true;game.bossWarning=true;data.daily.boss=true;save();$('#bossWarning').classList.remove('hidden');setTimeout(()=>{if(!game||game.ended)return;game.bossWarning=false;$('#bossWarning').classList.add('hidden');spawnBoss()},TEST?500:1800)}
function spawnBoss(){const hp=TEST?260:720,e={id:'boss',type:'boss',x:width()+95,y:groundY()-66,hp,max:hp,shield:TEST?80:220,shieldMax:TEST?80:220,phase:1,speed:110,damage:10,attack:1,hit:0,dead:false,death:0,rush:1};game.boss=e;game.enemies.push(e);$('#bossBar').classList.remove('hidden');$('#bossShieldBadge').classList.remove('hidden');updateBossHud()}
function damageEnemy(e,dmg,x,y){if(!e||e.dead)return;if(e.type==='boss'&&e.shield>0){const hit=dmg*.35;e.shield=Math.max(0,e.shield-hit);addFloater(x,y,'🛡 '+Math.round(hit),'#7dc9ff');if(e.shield<=0){toast('💥 '+t('bossShield'));$('#bossShieldBadge').classList.add('hidden');addParticles(e.x,e.y,28,'#7bdcff')}updateBossHud();return}e.hp-=dmg;e.hit=.12;addFloater(x,y,'-'+Math.round(dmg),'#fff3a4');if(e.type==='boss'){game.bossDamage+=dmg;const ratio=e.hp/e.max,next=ratio<.33?3:ratio<.66?2:1;if(next!==e.phase){e.phase=next;e.shield=Math.min(e.shieldMax,e.phase===2?90:130);$('#bossShieldBadge').classList.toggle('hidden',e.shield<=0);for(let i=0;i<e.phase+1;i++)spawnEnemy('elite');toast(`⚠ PHASE ${e.phase}`)}updateBossHud()}if(e.hp<=0){e.hp=0;e.dead=true;e.death=0;game.score+=e.type==='boss'?1800:{imp:35,bat:48,wolf:68,brute:95}[e.type];if(e.type==='boss'){toast('🏆 '+t('bossDown'));$('#bossBar').classList.add('hidden');game.boss=null;addParticles(e.x,e.y,60,'#ff6fd7')}else addParticles(e.x,e.y,14,'#ff79ce')}}
function removeEnemy(e){removeObj(game.enemies,e);if(game.focus===e)game.focus=null}
function removeObj(a,o){const i=a.indexOf(o);if(i>=0)a.splice(i,1)}
function poofUnit(u){addParticles(u.x,u.y,8,'#68eaff');addFloater(u.x,u.y-18,'✦','#ff9be4')}
function addParticles(x,y,n,color){if(!game)return;for(let i=0;i<n;i++){const life=rand(.25,.75);game.particles.push({x,y,vx:rand(-90,90),vy:rand(-110,30),g:140,life,max:life,a:1,color,size:rand(2,5)})}}
function addFloater(x,y,text,color){game.floaters.push({x,y,text,color,life:.75})}
function burstText(text,color){const el=$('#comboPop');el.textContent=text;el.style.color=color;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function screenShake(){$('#battleWrap').animate([{transform:'translateX(0)'},{transform:'translateX(-4px)'},{transform:'translateX(4px)'},{transform:'translateX(0)'}],{duration:220})}
function flash(kind){const el=$('#screenFlash');el.className='screenFlash '+kind;setTimeout(()=>el.className='screenFlash',520)}
function enemyRush(){for(const e of game.enemies)if(e.type!=='boss')e.rush=Math.max(e.rush,2.2);toast('⚠ '+t('rush'));screenShake()}
function collectSupply(){if(!game?.supply)return;const bonus=8+Math.floor(game.rng()*8);game.energy=clamp(game.energy+22,0,100);game.reserve+=bonus;addParticles(game.supply.x,game.supply.y,24,'#ffd86a');burstText(`+${bonus} 📦  +22⚡`,'#ffe077');game.supply=null;$('#supplyHint').classList.add('hidden');toast('🎁 '+t('supply'))}
function useSkill(kind){if(!game||game.ended)return;const cost={shot:25,shield:35,bomb:60}[kind];if(game.energy<cost){toast(t('notEnough'));return}game.energy-=cost;if(kind==='shot'){const target=chooseTarget();if(target){damageEnemy(target,target.type==='boss'?55:120,width()*.4,groundY()-110);beamFx(target);sfx(720,.09,'sawtooth')}}else if(kind==='shield'){game.shield=7;addParticles(80,groundY()-50,24,'#72c8ff');toast('🛡 7s')}else{for(const e of [...game.enemies])damageEnemy(e,e.type==='boss'?45:70,e.x,e.y);addParticles(width()*.55,groundY()-80,55,'#ff70d8');flash('good');screenShake();sfx(110,.18,'square')}}
function beamFx(target){game.projectiles.push({x:80,y:groundY()-90,tx:target,spd:1200,dmg:0,type:'beam',life:.25})}
function openQuestion(){if(!game||game.questionOpen)return;const fact=weightedFact(game.rng),modes=['choice','choice','inverse'];if(game.elapsed>45)modes.push('keypad');const mode=modes[Math.floor(game.rng()*modes.length)];game.q={...fact,mode};game.questionOpen=true;renderQuestion()}
function renderQuestion(){const q=game.q,p=$('#questionPanel');let display=q.ans,eq=`${q.a} × ${q.b} = ?`;if(q.mode==='inverse'){display=q.a;eq=`? × ${q.b} = ${q.ans}`}q.displayAns=display;if(q.mode==='keypad'){p.innerHTML=`<div class="qtop"><span>${esc(t('type'))}</span><span>⏳ ${esc(t('questionHint'))}</span></div><div class="equation">${eq}</div><div id="keyDisplay" class="keyDisplay">_</div><div class="keypad">${[1,2,3,4,5,6,7,8,9,0].map(n=>`<button class="key" data-key="${n}">${n}</button>`).join('')}</div><div class="actions"><button id="keyBack" class="btn">⌫</button><button id="keyGo" class="btn">OK</button></div>`;let buf='';p.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{if(buf.length<3){buf+=b.dataset.key;$('#keyDisplay').textContent=buf}});$('#keyBack').onclick=()=>{buf=buf.slice(0,-1);$('#keyDisplay').textContent=buf||'_'};$('#keyGo').onclick=()=>submitAnswer(Number(buf),$('#keyGo'))}else{const wrong=distract(display,game.rng),pair=game.rng()<.5?[display,wrong]:[wrong,display],icons=q.mode==='inverse'?['🔮','✨']:['⚔️','🎤'];p.innerHTML=`<div class="qtop"><span>${esc(q.mode==='inverse'?t('inverse'):t('choose'))}</span><span>⏳ ${esc(t('questionHint'))}</span></div><div class="equation">${eq}</div><div class="answers">${pair.map((v,i)=>`<button class="answer" data-answer="${v}"><span>${icons[i]}</span>${v}</button>`).join('')}</div>`;p.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submitAnswer(Number(b.dataset.answer),b))}p.classList.remove('hidden')}
function submitAnswer(v,btn){if(!game||!game.questionOpen||!Number.isFinite(v))return;const q=game.q,correct=v===q.displayAns;game.questionOpen=false;game.answers=(game.answers||0)+1;data.answered++;data.daily.answers++;if(correct){game.correct=(game.correct||0)+1;data.correct++;game.combo++;game.bestCombo=Math.max(game.bestCombo,game.combo);data.daily.maxCombo=Math.max(data.daily.maxCombo,game.combo);data.weak[q.key]=Math.max(0,(data.weak[q.key]||0)-1);const reward=q.displayAns;addTroops(reward);game.energy=clamp(game.energy+8+Math.floor(reward/10),0,100);game.score+=120+reward*2+game.combo*22;if(game.boss?.shield>0){game.boss.shield=Math.max(0,game.boss.shield-reward*1.2);if(game.boss.shield<=0){$('#bossShieldBadge').classList.add('hidden');toast('💥 '+t('bossShield'));addParticles(game.boss.x,game.boss.y,30,'#71d8ff')}updateBossHud()}if(btn)btn.classList.add('good');flash('good');burstText(`+${reward} ${t('reinforce')}`,'#7affc5');if(game.combo>=2)comboPop();sfx(540+Math.min(300,game.combo*35),.08,'triangle')}else{game.combo=0;data.weak[q.key]=Math.min(9,(data.weak[q.key]||0)+3);const selected=Math.max(0,Math.floor(v)),taken=deductTroops(selected);game.score=Math.max(0,game.score-30);if(btn)btn.classList.add('bad');flash('bad');burstText(`-${taken} ${t('lost')}`,'#ff8199');toast(`💡 ${t('answerWas')} ${q.displayAns}`);enemyRush();sfx(150,.12,'square')}save();setTimeout(()=>{$('#questionPanel').classList.add('hidden')},correct?580:1200)}
function comboPop(){const el=$('#comboPop');el.textContent=`🔥 ${game.combo} COMBO`;el.style.color='#ffd76d';el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function updateBossHud(){if(!game?.boss)return;const b=game.boss;$('#bossHpFill').style.width=clamp(b.hp/b.max*100,0,100)+'%';$('#bossShieldBadge').classList.toggle('hidden',b.shield<=0);$('#bossPhaseText').textContent=`DEMON STAGE MONARCH · PHASE ${b.phase}`}
function renderHud(){if(!game)return;$('#baseHp').textContent=Math.round(game.base);$('#frontlineCount').textContent=game.units.length;$('#reserveCount').textContent=game.reserve;$('#combo').textContent=game.combo;$('#score').textContent=Math.round(game.score).toLocaleString();$('#energyText').textContent=Math.round(game.energy);$('#energyFill').style.width=game.energy+'%';const s=Math.max(0,Math.ceil(game.time));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('#timeBar').style.width=(100-game.time/game.duration*100)+'%';$$('.skill').forEach(b=>{const cost=Number(b.dataset.cost);b.classList.toggle('disabled',game.energy<cost);b.classList.toggle('ready',game.energy>=cost)})}
function width(){return C?C.getBoundingClientRect().width:800}function height(){return C?C.getBoundingClientRect().height:400}function groundY(){return height()*.77}
function draw(){if(!ctx||!game)return;const W=width(),H=height();ctx.clearRect(0,0,W,H);drawBackground(W,H,game.stage);drawStageFloor(W,H,game.stage);drawBase(W,H);for(const u of game.units)drawUnit(u);for(const e of game.enemies)drawEnemy(e);for(const p of game.projectiles)drawProjectile(p);if(game.supply)drawSupply(game.supply);if(game.shield>0)drawShield();for(const p of game.particles){ctx.globalAlpha=p.a;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}for(const f of game.floaters){ctx.globalAlpha=clamp(f.life/.75,0,1);ctx.fillStyle=f.color;ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);ctx.globalAlpha=1}if(game.focus&&game.enemies.includes(game.focus)){ctx.strokeStyle='#ffe276';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.beginPath();ctx.ellipse(game.focus.x,game.focus.y,30,15,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}}
function drawBackground(W,H,th){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,th.sky1);g.addColorStop(.72,th.sky2);g.addColorStop(1,th.ground);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const tm=game.elapsed;
 if(th.id==='city'){drawCity(W,H,tm)}else if(th.id==='shrine'){drawShrine(W,H,tm)}else if(th.id==='ice'){drawIce(W,H,tm)}else drawLava(W,H,tm)}
function drawCity(W,H,tim){ctx.save();ctx.globalAlpha=.5;for(let i=0;i<5;i++){const x=W*(.12+i*.2),a=Math.sin(tim*.7+i)*.13;ctx.strokeStyle=i%2?'#ff63cf':'#5deaff';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(x,H*.02);ctx.lineTo(x+Math.sin(a)*70,H*.65);ctx.stroke()}ctx.globalAlpha=1;for(let i=0;i<14;i++){const w=36+(i%3)*18,x=i*(W/13)-20,h=45+(i%5)*18;ctx.fillStyle=i%2?'#111431':'#171139';ctx.fillRect(x,H*.53-h,w,h);ctx.fillStyle=i%3?'#59e4ff':'#ff5fc8';for(let y=0;y<h-12;y+=13)for(let xx=7;xx<w-7;xx+=15)if((xx+y+i)%4)ctx.fillRect(x+xx,H*.53-h+8+y,3,5)}ctx.fillStyle='rgba(255,255,255,.8)';for(let i=0;i<14;i++){const x=(i*137+tim*18)%W,y=25+(i*47)%100;ctx.fillRect(x,y,1.5,1.5)}ctx.restore()}
function drawShrine(W,H,tim){ctx.save();const mx=W*.78,my=H*.19,r=Math.min(W,H)*.16;const rg=ctx.createRadialGradient(mx-r*.2,my-r*.2,4,mx,my,r);rg.addColorStop(0,'#fff');rg.addColorStop(.35,'#ffd6fb');rg.addColorStop(1,'rgba(167,105,255,.15)');ctx.fillStyle=rg;ctx.beginPath();ctx.arc(mx,my,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(11,10,30,.75)';for(let i=0;i<5;i++){const x=W*(.12+i*.18),y=H*.5;ctx.fillRect(x-3,y-70,6,70);ctx.fillRect(x-26,y-70,52,5);ctx.fillRect(x-19,y-61,38,4)}for(let i=0;i<18;i++){const x=(i*97+tim*12)%W,y=30+(i*37)%180;ctx.fillStyle=i%2?'#ff8bd5':'#ffd2ec';ctx.beginPath();ctx.ellipse(x,y,3,1.6,tim+i,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawIce(W,H,tim){ctx.save();const ag=ctx.createLinearGradient(0,0,W,0);ag.addColorStop(0,'rgba(83,255,244,.12)');ag.addColorStop(.45,'rgba(183,116,255,.28)');ag.addColorStop(1,'rgba(76,221,255,.08)');ctx.fillStyle=ag;ctx.beginPath();ctx.moveTo(0,H*.18);for(let x=0;x<=W;x+=40)ctx.lineTo(x,H*.16+Math.sin(x*.015+tim*.5)*28);ctx.lineTo(W,H*.44);ctx.lineTo(0,H*.44);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(170,235,255,.35)';for(let i=0;i<8;i++){const x=i*W/7-30;ctx.beginPath();ctx.moveTo(x,H*.56);ctx.lineTo(x+70,H*.28-(i%3)*25);ctx.lineTo(x+130,H*.56);ctx.fill()}ctx.fillStyle='rgba(255,255,255,.8)';for(let i=0;i<26;i++){const x=(i*83+tim*14)%W,y=(i*61+tim*22)%H*.62;ctx.beginPath();ctx.arc(x,y,1.5+(i%3),0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawLava(W,H,tim){ctx.save();ctx.fillStyle='rgba(20,7,16,.75)';for(let i=0;i<9;i++){const x=i*W/8-50,peak=H*.28+(i%3)*26;ctx.beginPath();ctx.moveTo(x,H*.58);ctx.lineTo(x+70,peak);ctx.lineTo(x+150,H*.58);ctx.fill()}ctx.fillStyle='#ff6f2d';for(let i=0;i<10;i++){const x=(i*117+tim*20)%W,y=H*.48+(i%3)*12;ctx.beginPath();ctx.arc(x,y,4+Math.sin(tim+i)*2,0,Math.PI*2);ctx.fill()}for(let i=0;i<20;i++){const x=(i*71+tim*23)%W,y=H*.53-((i*29+tim*38)%160);ctx.fillStyle=i%2?'#ff934d':'#ffd26b';ctx.fillRect(x,y,2,4)}ctx.restore()}
function drawStageFloor(W,H,th){const y=groundY();ctx.fillStyle=th.ground;ctx.fillRect(0,y,W,H-y);ctx.strokeStyle=th.accent+'44';ctx.lineWidth=1;for(let x=-W;x<W*2;x+=70){ctx.beginPath();ctx.moveTo(W/2,y);ctx.lineTo(x,H);ctx.stroke()}for(let yy=y+18;yy<H;yy+=20){ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke()}}
function drawBase(W,H){const y=groundY();ctx.save();ctx.translate(18,y-110);ctx.shadowColor='#ff5fc8';ctx.shadowBlur=18;ctx.fillStyle='#17143f';roundRect(ctx,0,0,66,95,16,true,false);ctx.shadowBlur=0;ctx.fillStyle='#4f3aa2';ctx.fillRect(8,16,50,67);ctx.fillStyle='#5deaff';ctx.fillRect(18,28,30,8);ctx.fillStyle='#ff64c8';ctx.fillRect(18,45,30,8);ctx.fillStyle='#ffd866';ctx.beginPath();ctx.moveTo(33,4);ctx.lineTo(48,18);ctx.lineTo(18,18);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='900 10px system-ui';ctx.textAlign='center';ctx.fillText('STAGE',33,75);ctx.restore()}
function drawUnit(u){const s=.84+.36*u.spawn,x=u.x,y=u.y,hit=u.hit>0;ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.globalAlpha=hit?.65:1;ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,13,12,4,0,0,Math.PI*2);ctx.fill();const bounce=Math.sin(game.elapsed*7+u.x*.02)*1.2;ctx.translate(0,bounce);if(u.type==='blade')drawBladeHunter();else if(u.type==='blaster')drawBeatBlaster();else if(u.type==='shield')drawShieldDancer();else drawStarCannon();ctx.restore()}
function face(hair,skin='#ffd7c2'){ctx.fillStyle=skin;ctx.beginPath();ctx.arc(0,-13,7,0,Math.PI*2);ctx.fill();ctx.fillStyle=hair;ctx.beginPath();ctx.arc(0,-17,7.5,Math.PI,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-6,-17);ctx.lineTo(-2,-9);ctx.lineTo(1,-17);ctx.fill();ctx.fillStyle='#24153c';ctx.fillRect(-3,-13,1.4,1.4);ctx.fillRect(2,-13,1.4,1.4)}
function drawBladeHunter(){ctx.strokeStyle='#0d0b20';ctx.lineWidth=2;ctx.fillStyle='#ff4fbd';roundRect(ctx,-7,-7,14,18,5,true,true);face('#262352');ctx.strokeStyle='#6df5ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(6,-2);ctx.lineTo(17,-15);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(7,-3);ctx.lineTo(17,-15);ctx.stroke();ctx.fillStyle='#11112a';ctx.fillRect(-6,10,5,7);ctx.fillRect(2,10,5,7)}
function drawBeatBlaster(){ctx.strokeStyle='#0d0b20';ctx.lineWidth=2;ctx.fillStyle='#58dfff';roundRect(ctx,-7,-7,14,18,5,true,true);face('#52214c');ctx.fillStyle='#efefef';roundRect(ctx,5,-4,12,6,3,true,false);ctx.fillStyle='#ff5dbe';ctx.beginPath();ctx.arc(16,-1,3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-6,3);ctx.lineTo(4,3);ctx.stroke()}
function drawShieldDancer(){ctx.strokeStyle='#0d0b20';ctx.lineWidth=2;ctx.fillStyle='#9b75ff';roundRect(ctx,-7,-7,14,18,5,true,true);face('#f4b34e');ctx.fillStyle='#66ecff';ctx.beginPath();ctx.arc(11,1,8,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(11,1,5,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#17112e';ctx.fillRect(-6,10,5,7);ctx.fillRect(2,10,5,7)}
function drawStarCannon(){ctx.strokeStyle='#0d0b20';ctx.lineWidth=2;ctx.fillStyle='#ffd157';roundRect(ctx,-8,-7,16,18,5,true,true);face('#1a132d');ctx.fillStyle='#513878';roundRect(ctx,4,-3,16,9,4,true,false);ctx.fillStyle='#ff5ec3';ctx.beginPath();ctx.arc(20,1.5,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='900 8px system-ui';ctx.fillText('★',8,4)}
function drawEnemy(e){const x=e.x,y=e.y,death=e.dead?1-e.death/.35:1;ctx.save();ctx.translate(x,y);ctx.scale(death,death);if(e.hit>0){ctx.shadowColor='#fff';ctx.shadowBlur=18}ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,18,e.type==='boss'?34:18,6,0,0,Math.PI*2);ctx.fill();if(e.type==='imp')drawImp();else if(e.type==='bat')drawBat();else if(e.type==='wolf')drawWolf();else if(e.type==='brute')drawBrute();else drawBoss(e);ctx.shadowBlur=0;if(e.type!=='boss')drawHp(e,-26,-34,52,5);ctx.restore()}
function drawImp(){ctx.fillStyle='#8c4cff';ctx.beginPath();ctx.arc(0,-2,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff6ecf';ctx.beginPath();ctx.moveTo(-10,-13);ctx.lineTo(-4,-27);ctx.lineTo(0,-14);ctx.moveTo(10,-13);ctx.lineTo(4,-27);ctx.lineTo(0,-14);ctx.fill();eyes(0,-4);ctx.strokeStyle='#e8c9ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,2,5,.2,Math.PI-.2);ctx.stroke();ctx.fillStyle='#44216b';ctx.fillRect(-9,11,6,10);ctx.fillRect(3,11,6,10)}
function drawBat(){ctx.fillStyle='#30215a';for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(s*6,-5);ctx.lineTo(s*28,-20);ctx.lineTo(s*22,3);ctx.lineTo(s*10,7);ctx.fill()}ctx.fillStyle='#b14fff';ctx.beginPath();ctx.ellipse(0,-4,14,16,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff7acc';ctx.beginPath();ctx.moveTo(-8,-15);ctx.lineTo(-4,-27);ctx.lineTo(0,-15);ctx.fill();eyes(0,-7)}
function drawWolf(){ctx.fillStyle='#31304f';ctx.beginPath();ctx.ellipse(0,2,22,13,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(15,-8,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#895fff';ctx.beginPath();ctx.moveTo(8,-14);ctx.lineTo(10,-28);ctx.lineTo(16,-16);ctx.moveTo(18,-16);ctx.lineTo(25,-27);ctx.lineTo(24,-12);ctx.fill();ctx.fillStyle='#ff5cc5';ctx.fillRect(12,-10,3,3);ctx.fillRect(19,-10,3,3);ctx.strokeStyle='#6edfff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-19,-3);ctx.lineTo(-30,-14);ctx.stroke()}
function drawBrute(){ctx.fillStyle='#6d315e';roundRect(ctx,-21,-18,42,37,11,true,false);ctx.fillStyle='#2a173a';roundRect(ctx,-17,-14,34,13,7,true,false);ctx.fillStyle='#ff6a9a';ctx.fillRect(-9,-10,5,4);ctx.fillRect(5,-10,5,4);ctx.fillStyle='#8a5bff';ctx.fillRect(-27,-10,9,26);ctx.fillRect(18,-10,9,26);ctx.fillStyle='#31162e';ctx.fillRect(-14,18,10,12);ctx.fillRect(4,18,10,12);ctx.strokeStyle='#ffb05c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-15,-18);ctx.lineTo(-22,-29);ctx.moveTo(15,-18);ctx.lineTo(22,-29);ctx.stroke()}
function drawBoss(e){const pulse=1+Math.sin(game.elapsed*5)*.025;ctx.scale(pulse,pulse);ctx.fillStyle='rgba(255,70,200,.18)';ctx.beginPath();ctx.arc(0,-16,54,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3c194d';for(const s of [-1,1]){ctx.beginPath();ctx.moveTo(s*18,-5);ctx.lineTo(s*50,-28);ctx.lineTo(s*40,22);ctx.lineTo(s*20,28);ctx.fill()}ctx.fillStyle=e.phase===3?'#e33f79':'#7b2a85';roundRect(ctx,-27,-31,54,61,16,true,false);ctx.fillStyle='#15102e';ctx.beginPath();ctx.arc(0,-35,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f0bed1';ctx.beginPath();ctx.arc(0,-30,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1a102a';ctx.beginPath();ctx.arc(0,-37,13,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd75d';ctx.beginPath();ctx.moveTo(-14,-48);ctx.lineTo(-8,-64);ctx.lineTo(0,-50);ctx.lineTo(8,-65);ctx.lineTo(14,-48);ctx.closePath();ctx.fill();ctx.fillStyle='#ff58c6';ctx.fillRect(-6,-31,3,3);ctx.fillRect(4,-31,3,3);ctx.strokeStyle='#62eaff';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(22,-15);ctx.lineTo(38,-41);ctx.stroke();drawHp(e,-42,35,84,7);if(e.shield>0){ctx.strokeStyle='rgba(103,211,255,.75)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-10,49,0,Math.PI*2);ctx.stroke()}}
function eyes(x,y){ctx.fillStyle='#ffe165';ctx.fillRect(x-7,y,4,3);ctx.fillRect(x+3,y,4,3)}
function drawHp(e,x,y,w,h){ctx.fillStyle='rgba(20,8,30,.75)';roundRect(ctx,x,y,w,h,h/2,true,false);ctx.fillStyle=e.type==='boss'?'#ff4d9b':'#75f5a7';roundRect(ctx,x,y,w*clamp(e.hp/e.max,0,1),h,h/2,true,false)}
function drawProjectile(p){ctx.save();ctx.translate(p.x,p.y);if(p.type==='cannon'){ctx.fillStyle='#ffd467';ctx.shadowColor='#ff87d0';ctx.shadowBlur=9;ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill()}else if(p.type==='beam'){ctx.fillStyle='#fff';ctx.shadowColor='#62efff';ctx.shadowBlur=16;ctx.fillRect(-8,-2,20,4)}else{ctx.fillStyle=p.type==='blade'?'#ff7bd3':'#69eaff';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(0,0,3,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawSupply(s){ctx.save();ctx.translate(s.x,s.y+Math.sin(s.bob*4)*4);ctx.shadowColor='#ffd966';ctx.shadowBlur=18;ctx.fillStyle='#47265d';roundRect(ctx,-16,-14,32,28,7,true,false);ctx.fillStyle='#ffd65b';ctx.fillRect(-15,-4,30,5);ctx.fillRect(-3,-13,6,27);ctx.fillStyle='#fff';ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.fillText('⚡',0,4);ctx.restore()}
function drawShield(){ctx.save();ctx.strokeStyle='rgba(95,215,255,.75)';ctx.fillStyle='rgba(85,185,255,.10)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(82,groundY()-46,68,Math.PI*.6,Math.PI*1.4);ctx.stroke();ctx.fill();ctx.restore()}
function roundRect(c,x,y,w,h,r,fill,stroke){if(w<=0||h<=0)return;c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):(c.rect(x,y,w,h));if(fill)c.fill();if(stroke)c.stroke()}
function canvasTap(ev){if(!game||game.ended)return;const r=C.getBoundingClientRect(),x=(ev.touches?ev.touches[0].clientX:ev.clientX)-r.left,y=(ev.touches?ev.touches[0].clientY:ev.clientY)-r.top;if(game.supply&&Math.hypot(x-game.supply.x,y-game.supply.y)<36){collectSupply();return}let closest=null,dist=999;for(const e of game.enemies){const d=Math.hypot(x-e.x,y-e.y);if(d<dist&&d<55){closest=e;dist=d}}if(closest){game.focus=closest;addParticles(closest.x,closest.y,5,'#ffe36f');toast('🎯 Focus!')}}
function endGame(){if(!game||game.ended)return;game.ended=true;if(raf)cancelAnimationFrame(raf);raf=0;stopMusic();const answers=game.answers||0,correct=game.correct||0,acc=answers?correct/answers:0,coins=Math.max(8,Math.round(game.score/150)+correct*3),xpGain=Math.round(game.score/18)+correct*6;data.coins+=coins;data.xp+=xpGain;updateStreak();save();lastResult={seed:game.seed,score:Math.round(game.score),acc:Math.round(acc*100),combo:game.bestCombo,coins,xpGain,boss:game.bossDamage,bossMax:game.boss?.max||720,frontline:game.units.length,reserve:game.reserve,target:game.target,targetName:game.targetName};$('#resultScore').textContent=lastResult.score.toLocaleString();$('#resultAcc').textContent=lastResult.acc+'%';$('#resultCombo').textContent=lastResult.combo;$('#resultCoins').textContent='+'+coins;$('#resultBoss').textContent=Math.round(clamp(lastResult.boss/lastResult.bossMax*100,0,100))+'%';$('#resultFrontline').textContent=lastResult.frontline;$('#resultReserve').textContent=lastResult.reserve;$('#xpGain').textContent='+'+xpGain;$('#xpFill').style.width=Math.min(100,(data.xp%1000)/10)+'%';$('#resultTitle').textContent=acc>=.72?t('great'):t('practice');$('#lootReward').textContent=`✨ ${t('loot')}: ${['Neon Sticker','Star Shard','Stage Pass','Demon Badge'][Math.floor(Math.random()*4)]}`;if(lastResult.target!=null)$('#challengeBeat').textContent=(lastResult.score>lastResult.target?t('beat'):t('missed')+' '+lastResult.target)+(lastResult.targetName?' · '+lastResult.targetName:'');else $('#challengeBeat').textContent='';if(pendingChallenge){data.board=dedupeBoard([{n:data.nickname,score:lastResult.score,acc:lastResult.acc,ts:Date.now()},...data.board]);save()}coinRain();showScreen('result');pendingChallenge=null}
function coinRain(){const el=$('#coinRain');el.innerHTML='';for(let i=0;i<15;i++){const s=document.createElement('span');s.className='coinDrop';s.textContent='🪙';s.style.left=(5+Math.random()*90)+'%';s.style.animationDelay=(Math.random()*.6)+'s';el.appendChild(s)}}
function updateStreak(){const d=today();if(data.lastDay===d)return;const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);data.streak=data.lastDay===prev?data.streak+1:1;data.lastDay=d}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._tm);el._tm=setTimeout(()=>el.classList.remove('show'),1400)}
function renderCollection(){const av=[['🎤',0],['⚔️',100],['🎧',180],['🌟',300],['🪩',460],['👑',700]];$('#avatars').innerHTML=av.map(([e,c])=>itemHtml('avatar',e,c,data.avatar===e)).join('');const pets=[['',0,'—'],['🐱',180,'🐱'],['🦊',320,'🦊'],['🐲',560,'🐲']];$('#pets').innerHTML=pets.map(([v,c,l])=>itemHtml('pet',l,c,data.pet===v,v)).join('');$$('[data-collect]').forEach(b=>b.onclick=()=>selectCollect(b))}
function itemHtml(type,label,c,sel,val=label){const locked=data.coins<c;return `<button class="collectItem ${sel?'selected':''} ${locked?'locked':''}" data-collect="${type}" data-value="${esc(val)}" data-cost="${c}"><div class="big">${label}</div><b>${sel?t('selected'):locked?t('need')+' '+c+' 🪙':t('unlocked')}</b></button>`}
function selectCollect(b){const c=Number(b.dataset.cost);if(data.coins<c){toast(t('need')+' '+c+' 🪙');return}data[b.dataset.collect]=b.dataset.value;save();renderCollection();renderLobby()}
function renderProgress(){const acc=data.answered?Math.round(data.correct/data.answered*100):0;$('#lifeAcc').textContent=data.answered?acc+'%':'—';$('#lifeAnswered').textContent=data.answered;const all=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const k=i+'x'+j,w=data.weak[k]||0;if(w>0)all.push([k,w])}all.sort((a,b)=>b[1]-a[1]);$('#weakGrid').innerHTML=all.length?all.slice(0,15).map(([k,w])=>`<div class="weak"><b>${k.replace('x','×')}</b><div>${'⭐'.repeat(Math.min(3,Math.ceil(w/3)))}</div></div>`).join(''):'<div class="muted">No weak facts yet — play a round!</div>'}
function renderBoard(){const arr=[...data.board].sort((a,b)=>b.score-a.score);$('#boardList').innerHTML=arr.length?arr.map((x,i)=>`<div class="boardRow"><div class="rank">#${i+1}</div><div class="grow"><b>${esc(x.n)}</b><div class="muted">${x.acc||0}%</div></div><b>${Number(x.score).toLocaleString()}</b></div>`).join(''):`<div class="panel muted" style="padding:12px">${t('noBoard')}</div>`}
function makeCode(){if(!lastResult)return'';return b64e(JSON.stringify({v:3,n:data.nickname.slice(0,16),s:lastResult.seed,score:lastResult.score,acc:lastResult.acc}))}
function b64e(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64d(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return decodeURIComponent(escape(atob(s)))}
function parseCode(code){try{const clean=String(code).trim().replace(/^.*[?&]c=/,'').split('&')[0],o=JSON.parse(b64d(clean));if(![1,3].includes(o.v)||!o.n||!Number.isFinite(o.s)||!Number.isFinite(o.score))throw 0;return o}catch{return null}}
function loadChallenge(raw,alsoBoard=false){const o=parseCode(raw);if(!o){toast(t('invalidCode'));return false}pendingChallenge=o;if(alsoBoard){data.board=dedupeBoard([{n:o.n,score:o.score,acc:o.acc||0,ts:Date.now()},...data.board]);save();toast(t('imported'));renderBoard()}else{toast('🎯 '+t('challengeLoaded')+': '+o.n+' · '+o.score);setTimeout(startGame,450)}return true}
function dedupeBoard(a){const s=new Set;return a.filter(x=>{const k=x.n+'|'+x.score;if(s.has(k))return false;s.add(k);return true}).slice(0,30)}
function makeShare(){const code=makeCode();$('#shareCode').textContent=code;$('#shareArea').classList.remove('hidden');const url=location.origin+location.pathname+'?c='+encodeURIComponent(code);setTimeout(()=>{try{if(window.QRious)new QRious({element:$('#qr'),value:url,size:144,level:'M'});else{const q=$('#qr').getContext('2d');q.fillStyle='#fff';q.fillRect(0,0,144,144);q.fillStyle='#111';q.font='11px sans-serif';q.fillText('Use challenge code',18,72)}}catch{}},30);$('#shareBtn').dataset.url=url}
async function share(){const code=makeCode(),url=$('#shareBtn').dataset.url||location.href,text=t('shareText')+'\n'+data.nickname+': '+lastResult.score+' pts\n'+code;try{if(navigator.share)await navigator.share({title:t('shareTitle'),text,url});else prompt('Copy challenge code:',code)}catch{}}
function startMusic(){if(!data.music)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let step=0;clearInterval(musicTimer);musicTimer=setInterval(()=>{if(!game||game.ended||!data.music)return;const notes=[261.6,329.6,392,523.2,440,392,349.2,493.9];sfx(notes[step++%notes.length],.06,'triangle',.025)},330)}catch{}}
function stopMusic(){clearInterval(musicTimer);musicTimer=0}
function sfx(freq,dur,type='sine',gain=.05){try{if(!data.music)return;audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch{}}
function toggleMusic(){data.music=!data.music;save();$('#musicBtn').textContent=data.music?'🔊':'🔇';if(data.music&&game&&!game.ended)startMusic();else stopMusic()}
$('#langBtn').onclick=()=>{data.lang=data.lang==='en'?'zh':'en';save();applyLang()};$('#musicBtn').onclick=toggleMusic;$('#playBtn').onclick=()=>{pendingChallenge=null;startGame()};$('#settingsBtn').onclick=openSetup;$('#setupForm').onsubmit=e=>{e.preventDefault();const n=$('#nicknameInput').value.trim().replace(/[^\p{L}\p{N}_\- ]/gu,'').slice(0,16);if(!n)return;data.nickname=n;data.focus=$('#focusSelect').value;save();$('#setupModal').classList.add('hidden');renderLobby()};$$('[data-open]').forEach(b=>b.onclick=()=>showScreen(b.dataset.open));$$('.backBtn').forEach(b=>b.onclick=()=>showScreen('lobby'));$('#loadChallengeBtn').onclick=()=>loadChallenge($('#challengeInput').value);$('#importBoardBtn').onclick=()=>loadChallenge($('#boardCode').value,true);$('#retryBtn').onclick=startGame;$('#homeBtn').onclick=()=>showScreen('lobby');$('#makeChallengeBtn').onclick=makeShare;$('#shareBtn').onclick=share;$('#dismissRotate').onclick=()=>{rotateDismissed=true;$('#rotatePrompt').classList.remove('show');$('#rotatePrompt').classList.add('dismissed')};$('#skillShot').onclick=()=>useSkill('shot');$('#skillShield').onclick=()=>useSkill('shield');$('#skillBomb').onclick=()=>useSkill('bomb');addEventListener('resize',()=>{checkRotate();resizeCanvas()});addEventListener('orientationchange',()=>setTimeout(()=>{checkRotate();resizeCanvas()},250));$('#battleCanvas').addEventListener('pointerdown',canvasTap);
window.__TTA_TEST__={startGame,openQuestion,submitAnswer,useSkill,collectSupply,endGame,getGame:()=>game,getData:()=>data,totalTroops,parseCode,makeCode,forceBoss:()=>{if(game&&!game.bossStarted)startBossSequence()},setEnergy:v=>{if(game)game.energy=v},setTroops:(front,res)=>{if(!game)return;game.units=[];game.reserve=res;for(let i=0;i<Math.min(front,FRONT_CAP);i++)spawnUnit(true)},spawnEnemy:()=>spawnEnemy(null)};
ensureDaily();$('#musicBtn').textContent=data.music?'🔊':'🔇';applyLang();if(!data.nickname)openSetup();const incoming=new URLSearchParams(location.search).get('c');if(incoming){$('#challengeInput').value=incoming;const o=parseCode(incoming);if(o){pendingChallenge=o;toast('🎯 '+t('challengeLoaded')+': '+o.n)}}checkRotate();