'use strict';
const TEST=new URLSearchParams(location.search).get('test')==='1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='tta_v1';
const defaults={nickname:'',lang:'en',coins:0,xp:0,streak:0,lastDay:'',avatar:'🧑‍🚀',pet:'',music:true,focus:'auto',answered:0,correct:0,weak:{},board:[],daily:{day:'',answers:0,maxCombo:0,boss:false}};
let data=load();
let game=null, raf=0, lastTs=0, audio=null, musicTimer=0, lastResult=null, pendingChallenge=null, rotateDismissed=false;
const I18N={
 en:{welcome:'Welcome back',coins:'Coins',streak:'Streak',todayMissions:"Today’s missions",collection:'Collection',progress:'My Progress',classboard:'Classboard',settings:'Settings',load:'Load',how:'How it works',howText:'Fight, dodge and collect. A maths challenge appears only every 25–40 seconds. Correct answers boost your army. Wrong answers teach the fact and bring it back later.',runComplete:'Run complete',accuracy:'Accuracy',bestCombo:'Best combo',coinsEarned:'Coins earned',bossDamage:'Boss damage',retry:'Play again',challengeFriend:'Challenge a friend',home:'Home',share:'Share',collectionHint:'Use coins to unlock. Pets give tiny, fair bonuses.',avatars:'Avatars',pets:'Pets',lifetimeAccuracy:'Lifetime accuracy',factsAnswered:'Facts answered',weakFacts:'Facts to practise',boardHint:'No account needed. Import classmates’ challenge codes and their scores appear here on this device.',import:'Import',rotate:'Rotate your phone',rotateText:'This game is designed for landscape mode.',continueAnyway:'Continue anyway',setupTitle:'Player setup',nickname:'Nickname',focus:'Training focus',save:'Save',missionA:'Answer 20 facts',missionB:'Reach 5 combo',missionC:'Reach the Boss',ready:'Ready?',correct:'Correct!',wrong:'Not quite',answerWas:'Answer:',powerUp:'Power up!',armyPlus:'Army +',revive:'Free revive!',boss:'FINAL BOSS',challengeLoaded:'Challenge loaded',invalidCode:'Invalid challenge code',imported:'Classmate imported',noBoard:'No classmates imported yet.',beat:'You beat the challenge!',missed:'Target:',target:'Target',tap:'Tap the correct answer',type:'Type the answer',lane:'Choose a lane',monster:'Hit the correct monster',bridge:'Build the bridge',balloon:'Pop the correct balloon',inverse:'Find the missing number',great:'Great run!',practice:'Keep building your army!',shareTitle:'Times Table Arena challenge',shareText:'Can you beat my Times Table Arena score?',unlocked:'Unlocked',need:'Need',selected:'Selected',focusAuto:'Adaptive 1×1–10×10'},
 zh:{welcome:'歡迎返嚟',coins:'金幣',streak:'連續日數',todayMissions:'今日任務',collection:'收藏',progress:'學習進度',classboard:'同學榜',settings:'設定',load:'載入',how:'玩法',howText:'戰鬥、收集、升級。數學題只會大約每 25–40 秒出現一次；答啱會強化軍隊，答錯會顯示正確答案，之後再練。',runComplete:'完成一局',accuracy:'正確率',bestCombo:'最高連擊',coinsEarned:'獲得金幣',bossDamage:'Boss 傷害',retry:'再玩一次',challengeFriend:'挑戰同學',home:'主頁',share:'分享',collectionHint:'用金幣解鎖。寵物只有輕微能力，保持公平。',avatars:'角色',pets:'寵物',lifetimeAccuracy:'總正確率',factsAnswered:'已完成題目',weakFacts:'需要多練習',boardHint:'毋須帳戶。輸入同學 Challenge Code，就可以將佢哋成績加入本機同學榜。',import:'加入',rotate:'請將手機轉為橫向',rotateText:'本遊戲以橫向畫面設計，玩起來會更舒服。',continueAnyway:'照樣繼續',setupTitle:'玩家設定',nickname:'暱稱',focus:'練習重點',save:'儲存',missionA:'完成 20 題',missionB:'達成 5 Combo',missionC:'打到 Boss',ready:'準備！',correct:'答啱！',wrong:'差少少',answerWas:'正確答案：',powerUp:'火力升級！',armyPlus:'士兵 +',revive:'免費復活！',boss:'最終 Boss',challengeLoaded:'挑戰已載入',invalidCode:'Challenge Code 無效',imported:'已加入同學成績',noBoard:'暫時未加入同學成績。',beat:'你打破咗同學成績！',missed:'目標：',target:'挑戰目標',tap:'按正確答案',type:'輸入答案',lane:'揀正確路線',monster:'攻擊正確怪物',bridge:'砌出正確橋樑',balloon:'篤爆正確氣球',inverse:'找出缺少的數字',great:'打得好！',practice:'繼續升級你嘅軍隊！',shareTitle:'Times Table Arena 挑戰',shareText:'你可唔可以打破我嘅 Times Table Arena 分數？',unlocked:'已解鎖',need:'需要',selected:'使用中',focusAuto:'自動 1×1–10×10'}
};
function t(k){return (I18N[data.lang]&&I18N[data.lang][k])||I18N.en[k]||k}
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return {...defaults}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){}}
function today(){return new Date().toISOString().slice(0,10)}
function ensureDaily(){if(data.daily.day!==today())data.daily={day:today(),answers:0,maxCombo:0,boss:false}}
function applyLang(){document.documentElement.lang=data.lang==='zh'?'zh-Hant':'en';$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});$('#langBtn').textContent=data.lang==='en'?'繁中':'EN';$('#challengeInput').placeholder=data.lang==='zh'?'貼上 Challenge Code':'Paste challenge code';$('#boardCode').placeholder=$('#challengeInput').placeholder;renderLobby()}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='lobby')renderLobby();if(id==='collection')renderCollection();if(id==='progress')renderProgress();if(id==='board')renderBoard();checkRotate()}
function checkRotate(){const gameish=$('#game').classList.contains('active')||$('#lobby').classList.contains('active');const portrait=innerHeight>innerWidth&&innerWidth<900;if(gameish&&portrait&&!rotateDismissed)$('#rotatePrompt').classList.add('show');else $('#rotatePrompt').classList.remove('show')}
function renderLobby(){ensureDaily();$('#heroAvatar').textContent=data.avatar+(data.pet?data.pet:'');$('#nickLabel').textContent=data.nickname||'Player';$('#coinsLabel').textContent=data.coins;$('#xpLabel').textContent=data.xp;$('#streakLabel').textContent=data.streak+'🔥';$('#focusLabel').textContent=data.focus==='auto'?t('focusAuto'):'×'+data.focus;const d=data.daily;const ms=[{n:t('missionA'),v:Math.min(d.answers,20),m:20},{n:t('missionB'),v:Math.min(d.maxCombo,5),m:5},{n:t('missionC'),v:d.boss?1:0,m:1}];$('#missions').innerHTML=ms.map(m=>`<div class="mission"><b>${esc(m.n)}</b><div class="sub">${m.v}/${m.m}</div><div class="bar"><i style="width:${m.v/m.m*100}%"></i></div></div>`).join('');}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openSetup(){$('#nicknameInput').value=data.nickname;$('#focusSelect').value=data.focus;$('#setupModal').classList.remove('hidden')}
function seedRand(seed){let x=seed>>>0;return()=>{x+=0x6D2B79F5;let z=x;z=Math.imul(z^(z>>>15),z|1);z^=z+Math.imul(z^(z>>>7),z|61);return((z^(z>>>14))>>>0)/4294967296}}
function weightedFact(rng){let a,b;const focus=Number(data.focus)||0;if(focus){a=focus;b=1+Math.floor(rng()*10)}else{let pool=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const key=i+'x'+j;const w=1+Math.min(6,Number(data.weak[key]||0));for(let k=0;k<w;k++)pool.push([i,j])}[a,b]=pool[Math.floor(rng()*pool.length)]}return {a,b,ans:a*b,key:a+'x'+b}}
function makeDistractor(ans,rng){const deltas=[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,1,2,3,4,5,6,7,8,9,10];let d=ans+deltas[Math.floor(rng()*deltas.length)];if(d<=0||d===ans)d=ans+1+Math.floor(rng()*5);return d}
