function startGame(){if(!data.nickname){openSetup();return}ensureDaily();stopGame();const seed=pendingChallenge?pendingChallenge.s:Math.floor(Math.random()*2147483647);const duration=TEST?24:360;game={seed,rng:seedRand(seed),duration,time:duration,score:0,combo:0,bestCombo:0,soldiers:5,power:1,base:100,answers:0,correct:0,bossDamage:0,boss:false,bossHp:0,bossMax:0,enemies:[],nextQ:TEST?2:8+Math.random()*8,q:null,questionOpen:false,revive:true,target:pendingChallenge?pendingChallenge.score:null,targetName:pendingChallenge?pendingChallenge.n:null,lastSpawn:0,lastCombat:0,elapsed:0};$('#shareArea').style.display='none';showScreen('game');renderSoldiers();startMusic();toast(t('ready'));lastTs=performance.now();raf=requestAnimationFrame(loop)}
function stopGame(){if(raf)cancelAnimationFrame(raf);raf=0;game&&game.enemies&&game.enemies.forEach(e=>e.el&&e.el.remove());$('#enemies').innerHTML='';$('#questionPanel').classList.add('hidden')}
function loop(ts){if(!game||game.ended)return;const dt=Math.min(.05,(ts-lastTs)/1000||0);lastTs=ts;tick(dt);renderHud();raf=requestAnimationFrame(loop)}
function tick(dt){game.time-=dt;game.elapsed+=dt;const progress=1-game.time/game.duration;if(!game.boss&&progress>.76){game.boss=true;data.daily.boss=true;save();spawnBoss();$('#bossBanner').classList.add('show');toast(t('boss'))}if(game.time<=0){endGame();return}const slow=game.questionOpen ? .25 : 1;game.lastSpawn+=dt;if(game.lastSpawn>(TEST ? .7 : Math.max(.85,1.85-progress*.7))){game.lastSpawn=0;spawnEnemy(false)}game.lastCombat+=dt;if(game.lastCombat>.55){game.lastCombat=0;combatTick()}for(const e of [...game.enemies]){if(e.boss)continue;e.x-=e.speed*dt*slow;if(e.x<84){game.base=Math.max(0,game.base-e.damage);removeEnemy(e);$('#base').classList.add('shake');setTimeout(()=>$('#base').classList.remove('shake'),350);if(game.base<=0){if(game.revive){game.revive=false;game.base=42;game.soldiers=Math.max(3,game.soldiers);toast(t('revive'))}else{endGame();return}}else e.el.style.transform=`translateX(${e.x}px)`}game.nextQ-=dt;if(game.nextQ<=0&&!game.questionOpen){openQuestion();game.nextQ=TEST?3.4:25+game.rng()*15}}}
function spawnEnemy(forceLarge){if(!game||game.ended)return;const p=game.elapsed/game.duration;let type=forceLarge?'large':(game.rng()<.58?'small':game.rng()<.78?'mid':'large');const hpBase={small:10,mid:20,large:35}[type];const hp=Math.round(hpBase*(1+p*1.9));const e={type,hp,max:hp,damage:{small:4,mid:7,large:11}[type],speed:TEST?120:42+p*20,x:Math.max(430,innerWidth-80),boss:false};e.el=document.createElement('div');e.el.className='enemy '+type;e.el.innerHTML=`<div class="hp"><i style="width:100%"></i></div>${type==='small'?'👾':type==='mid'?'👹':'🦖'}`;e.el.style.transform=`translateX(${e.x}px)`;$('#enemies').appendChild(e.el);game.enemies.push(e)}
function spawnBoss(){const hp=TEST?110:520+Math.round(game.elapsed*1.2);const e={type:'boss',hp,max:hp,damage:0,speed:0,x:Math.max(440,innerWidth-150),boss:true};game.bossHp=hp;game.bossMax=hp;e.el=document.createElement('div');e.el.className='enemy boss';e.el.innerHTML=`<div class="hp"><i></i></div>👹`;e.el.style.transform=`translateX(${e.x}px)`;$('#enemies').appendChild(e.el);game.enemies.push(e);updateEnemyHp(e)}
function combatTick(){if(!game.enemies.length)return;const boss=game.enemies.find(e=>e.boss);const target=boss||game.enemies.reduce((a,b)=>a.x<b.x?a:b);const dmg=Math.max(1,Math.round(game.soldiers*game.power*(.24+game.rng()*.12)));target.hp-=dmg;if(target.boss)game.bossDamage+=dmg;updateEnemyHp(target);if(target.hp<=0){game.score+=target.boss?1200:{small:25,mid:45,large:75}[target.type];if(target.boss){removeEnemy(target);$('#bossBanner').classList.remove('show');toast('🏆 BOSS DOWN!');game.power+=.35}else removeEnemy(target)}}
function updateEnemyHp(e){const i=e.el.querySelector('.hp i');if(i)i.style.width=Math.max(0,e.hp/e.max*100)+'%'}
function removeEnemy(e){const idx=game.enemies.indexOf(e);if(idx>=0)game.enemies.splice(idx,1);e.el&&e.el.remove()}
function renderSoldiers(){const n=Math.min(8,game?game.soldiers:5);$('#soldiers').innerHTML=Array.from({length:n},(_,i)=>`<span class="soldier" style="transform:translateY(${(i%2)*4}px)">🪖</span>`).join('')}
function renderHud(){if(!game)return;$('#baseHp').textContent=Math.round(game.base);$('#soldierCount').textContent=game.soldiers;$('#combo').textContent=game.combo;$('#score').textContent=Math.round(game.score);$('#rewardBox').textContent=`⚡ Power ${game.power.toFixed(1)}×`;const s=Math.max(0,Math.ceil(game.time));$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('#timeBar').style.width=(100-game.time/game.duration*100)+'%'}
function openQuestion(){const fact=weightedFact(game.rng);const modes=['lane','monster','bridge','balloon'];if(game.elapsed/game.duration>.3)modes.push('keypad');if(game.elapsed/game.duration>.45)modes.push('inverse');const mode=modes[Math.floor(game.rng()*modes.length)];game.q={...fact,mode};game.questionOpen=true;renderQuestion()}
function renderQuestion(){const q=game.q,p=$('#questionPanel');let eq=`${q.a} × ${q.b} = ?`, prompt=t('tap');if(q.mode==='inverse'){eq=`? × ${q.b} = ${q.ans}`;prompt=t('inverse');q.displayAns=q.a}else q.displayAns=q.ans;const wrong=makeDistractor(q.displayAns,game.rng);const pair=game.rng()<.5?[q.displayAns,wrong]:[wrong,q.displayAns];if(q.mode==='keypad'){p.innerHTML=`<div class="qtop"><span class="qtype">${esc(t('type'))}</span><span>⏳ slow-motion</span></div><div class="equation">${eq}</div><div class="keyDisplay" id="keyDisplay">_</div><div class="keypad">${[1,2,3,4,5,6,7,8,9,0].map(n=>`<button class="key" data-key="${n}">${n}</button>`).join('')}</div><div class="actions"><button class="secondary" id="keyBack">⌫</button><button class="secondary" id="keyGo">OK</button></div>`;let buf='';p.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{if(buf.length<3){buf+=b.dataset.key;$('#keyDisplay').textContent=buf}}));$('#keyBack').addEventListener('click',()=>{buf=buf.slice(0,-1);$('#keyDisplay').textContent=buf||'_'});$('#keyGo').addEventListener('click',()=>submitAnswer(Number(buf),$('#keyGo')))}else{const label={lane:t('lane'),monster:t('monster'),bridge:t('bridge'),balloon:t('balloon'),inverse:t('inverse')}[q.mode]||prompt;const emoji={lane:['⬅️','➡️'],monster:['👾','👹'],bridge:['🪨','🪨'],balloon:['🎈','🎈'],inverse:['🔢','🔢']}[q.mode];p.innerHTML=`<div class="qtop"><span class="qtype">${esc(label)}</span><span>⏳ slow-motion</span></div><div class="equation">${eq}</div><div class="answers">${pair.map((v,i)=>`<button class="answer" data-answer="${v}"><span class="emoji">${emoji[i]}</span>${v}</button>`).join('')}</div>`;p.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>submitAnswer(Number(b.dataset.answer),b)))}p.classList.remove('hidden')}
function submitAnswer(v,btn){if(!game||!game.questionOpen)return;const q=game.q,correct=v===q.displayAns;game.answers++;data.answered++;data.daily.answers++;if(correct){game.correct++;data.correct++;game.combo++;game.bestCombo=Math.max(game.bestCombo,game.combo);data.daily.maxCombo=Math.max(data.daily.maxCombo,game.combo);data.weak[q.key]=Math.max(0,(data.weak[q.key]||0)-1);const add=2+Math.floor(game.combo/4);game.soldiers=Math.min(24,game.soldiers+add);game.score+=110+game.combo*18;if(game.combo%5===0){game.power=Math.min(4,game.power+.28);toast('⚡ '+t('powerUp'))}else toast('✅ '+t('correct')+' · '+t('armyPlus')+add);if(btn)btn.classList.add('good')}else{game.combo=0;data.weak[q.key]=Math.min(8,(data.weak[q.key]||0)+3);game.score=Math.max(0,game.score-20);if(btn)btn.classList.add('bad');toast('💡 '+t('answerWas')+' '+q.displayAns)}save();renderSoldiers();setTimeout(()=>{if(game&&!game.ended){$('#questionPanel').classList.add('hidden');game.questionOpen=false}},correct?520:1100)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._tm);el._tm=setTimeout(()=>el.classList.remove('show'),1400)}
function endGame(){if(!game||game.ended)return;game.ended=true;if(raf)cancelAnimationFrame(raf);raf=0;stopMusic();const acc=game.answers?game.correct/game.answers:0;const coins=Math.max(5,Math.round(game.score/130)+game.correct*2);data.coins+=coins;data.xp+=Math.round(game.score/20)+game.correct*5;updateStreak();save();lastResult={seed:game.seed,score:Math.round(game.score),acc:Math.round(acc*100),combo:game.bestCombo,coins,boss:Math.min(game.bossMax||1,game.bossDamage),bossMax:game.bossMax||1,target:game.target,targetName:game.targetName};$('#resultScore').textContent=lastResult.score.toLocaleString();$('#resultAcc').textContent=lastResult.acc+'%';$('#resultCombo').textContent=lastResult.combo;$('#resultCoins').textContent='+'+coins;$('#resultBoss').textContent=Math.round(lastResult.boss/lastResult.bossMax*100)+'%';$('#resultTitle').textContent=acc>=.75?t('great'):t('practice');if(lastResult.target!=null){$('#challengeBeat').textContent=(lastResult.score>lastResult.target?t('beat'):t('missed')+' '+lastResult.target)+(lastResult.targetName?' · '+lastResult.targetName:'')}else $('#challengeBeat').textContent='';if(pendingChallenge){data.board=dedupeBoard([{n:data.nickname,score:lastResult.score,acc:lastResult.acc,ts:Date.now()},...data.board]);save()}showScreen('result');game.enemies.forEach(e=>e.el&&e.el.remove());game.enemies=[];pendingChallenge=null}
function updateStreak(){const d=today();if(data.lastDay===d)return;const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);data.streak=data.lastDay===prev?data.streak+1:1;data.lastDay=d}
function makeCode(){if(!lastResult)return'';const obj={v:1,n:data.nickname.slice(0,16),s:lastResult.seed,score:lastResult.score,acc:lastResult.acc};return b64e(JSON.stringify(obj))}
function b64e(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64d(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return decodeURIComponent(escape(atob(s)))}
function parseCode(code){try{const clean=String(code).trim().replace(/^.*[?&]c=/,'').split('&')[0];const o=JSON.parse(b64d(clean));if(o.v!==1||!o.n||!Number.isFinite(o.s)||!Number.isFinite(o.score))throw 0;return o}catch(e){return null}}
function loadChallenge(raw,alsoBoard=false){const o=parseCode(raw);if(!o){toast(t('invalidCode'));return false}pendingChallenge=o;if(alsoBoard){data.board=dedupeBoard([{n:o.n,score:o.score,acc:o.acc||0,ts:Date.now()},...data.board]);save();toast(t('imported'));renderBoard()}else{toast('🎯 '+t('challengeLoaded')+': '+o.n+' · '+o.score);setTimeout(startGame,500)}return true}
function dedupeBoard(arr){const seen=new Set();return arr.filter(x=>{const k=x.n+'|'+x.score;if(seen.has(k))return false;seen.add(k);return true}).slice(0,30)}
