function makeShare(){const code=makeCode();$('#shareCode').textContent=code;$('#shareArea').style.display='block';const url=location.origin+location.pathname+'?c='+encodeURIComponent(code);setTimeout(()=>{try{if(window.QRious)new QRious({element:$('#qr'),value:url,size:150,level:'M'});else{const ctx=$('#qr').getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,150,150);ctx.fillStyle='#111';ctx.font='12px sans-serif';ctx.fillText('QR library unavailable',8,75)}}catch(e){}},50);$('#shareBtn').dataset.url=url}
async function share(){const code=makeCode(),url=$('#shareBtn').dataset.url||location.href;const text=t('shareText')+'\n'+data.nickname+': '+lastResult.score+' pts\n'+code;try{if(navigator.share)await navigator.share({title:t('shareTitle'),text,url});else{prompt('Copy challenge code:',code)}}catch(e){}}
function renderCollection(){const av=[['🧑‍🚀',0],['🥷',80],['🧙',160],['🦸',260],['🤖',400],['🐉',650]];$('#avatars').innerHTML=av.map(([emo,c])=>itemHtml('avatar',emo,c,data.avatar===emo)).join('');const pets=[['',0,'—'],['🐶',180,'🐶'],['🐱',300,'🐱'],['🦊',520,'🦊']];$('#pets').innerHTML=pets.map(([emo,c,label])=>itemHtml('pet',label,c,data.pet===emo,emo)).join('');$$('[data-collect]').forEach(b=>b.addEventListener('click',()=>selectCollect(b)))}
function itemHtml(type,label,c,sel,val=label){const locked=data.coins<c;return `<button class="collectItem ${sel?'selected':''} ${locked?'locked':''}" data-collect="${type}" data-value="${esc(val)}" data-cost="${c}"><div class="big">${label}</div><b>${sel?t('selected'):locked?t('need')+' '+c+' 🪙':t('unlocked')}</b></button>`}
function selectCollect(b){const c=Number(b.dataset.cost);if(data.coins<c){toast(t('need')+' '+c+' 🪙');return}data[b.dataset.collect]=b.dataset.value;save();renderCollection();renderLobby()}
function renderProgress(){const acc=data.answered?Math.round(data.correct/data.answered*100):0;$('#lifeAcc').textContent=data.answered?acc+'%':'—';$('#lifeAnswered').textContent=data.answered;const all=[];for(let i=1;i<=10;i++)for(let j=1;j<=10;j++){const k=i+'x'+j,w=data.weak[k]||0;if(w>0)all.push([k,w])}all.sort((a,b)=>b[1]-a[1]);$('#weakGrid').innerHTML=(all.slice(0,15).map(([k,w])=>`<div class="weak"><b>${k.replace('x','×')}</b><div>${'⭐'.repeat(Math.min(3,Math.ceil(w/3)))}</div></div>`).join(''))||`<div class="sub">No weak facts yet — play a round!</div>`}
function renderBoard(){const arr=[...data.board].sort((a,b)=>b.score-a.score);$('#boardList').innerHTML=arr.length?arr.map((x,i)=>`<div class="row"><div class="rank">#${i+1}</div><div class="grow"><b>${esc(x.n)}</b><div class="sub">${x.acc||0}% accuracy</div></div><b>${Number(x.score).toLocaleString()}</b></div>`).join(''):`<div class="card sub">${t('noBoard')}</div>`}
function startMusic(){if(!data.music)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let step=0;clearInterval(musicTimer);musicTimer=setInterval(()=>{if(!game||game.ended||!data.music)return;const notes=[261.6,329.6,392,329.6,293.7,349.2,440,349.2];const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=notes[step++%notes.length];g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.16);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.17)},360)}catch(e){}}
function stopMusic(){clearInterval(musicTimer);musicTimer=0}
function toggleMusic(){data.music=!data.music;save();$('#musicBtn').textContent=data.music?'🔊':'🔇';if(data.music&&game&&!game.ended)startMusic();else stopMusic()}
$('#langBtn').addEventListener('click',()=>{data.lang=data.lang==='en'?'zh':'en';save();applyLang()});$('#musicBtn').addEventListener('click',toggleMusic);$('#playBtn').addEventListener('click',()=>{pendingChallenge=null;startGame()});$('#settingsBtn').addEventListener('click',openSetup);$('#setupForm').addEventListener('submit',e=>{e.preventDefault();const n=$('#nicknameInput').value.trim().replace(/[^\p{L}\p{N}_\- ]/gu,'').slice(0,16);if(!n)return;data.nickname=n;data.focus=$('#focusSelect').value;save();$('#setupModal').classList.add('hidden');renderLobby()});$$('[data-open]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.open)));$$('.backBtn').forEach(b=>b.addEventListener('click',()=>showScreen('lobby')));$('#loadChallengeBtn').addEventListener('click',()=>loadChallenge($('#challengeInput').value));$('#importBoardBtn').addEventListener('click',()=>loadChallenge($('#boardCode').value,true));$('#retryBtn').addEventListener('click',()=>startGame());$('#homeBtn').addEventListener('click',()=>showScreen('lobby'));$('#makeChallengeBtn').addEventListener('click',makeShare);$('#shareBtn').addEventListener('click',share);$('#dismissRotate').addEventListener('click',()=>{rotateDismissed=true;$('#rotatePrompt').classList.remove('show');$('#rotatePrompt').classList.add('dismissed')});addEventListener('resize',checkRotate);addEventListener('orientationchange',()=>setTimeout(checkRotate,250));
window.__TTA_TEST__={startGame,openQuestion,renderQuestion,submitAnswer,endGame,getData:()=>data,getGame:()=>game,parseCode,makeCode};
ensureDaily();$('#musicBtn').textContent=data.music?'🔊':'🔇';applyLang();if(!data.nickname)openSetup();const incoming=new URLSearchParams(location.search).get('c');if(incoming){$('#challengeInput').value=incoming;const o=parseCode(incoming);if(o){pendingChallenge=o;toast('🎯 '+t('challengeLoaded')+': '+o.n)}}checkRotate();
